### PR TITLE
Eve fix 2015 v1.1

### PR DESCRIPTION
**Pull request by regit**
Fixing Travis build of #1323: build was failing if libjansson was not available

PR builds:
- PR build: https://buildbot.openinfosecfoundation.org/builders/regit/builds/34
- PR pcaps: https://buildbot.openinfosecfoundation.org/builders/regit-pcap/builds/32

### CODE REVIEW

**Comment by inliniac** [comment]
Is there a special reason for moving things into OutputJsonCtx and not LogFileCtx? The latter already has some support for different methods (for tile) and then syslog would work for all outputs, not just EVE.

**Comment by regit** [comment]
@inliniac not really. I've fixed a typing issue in fd3c1ab and the logical progression behind that was to use OutputJsonCtx as transfer point. The other point I had in mind is that JSON was text so we had a specific type of data that may not mixed correctly with other types (thinking to unified2 for example).

**Comment by inliniac** [comment]
I don't see a good case of having these parallel constructs. I think we can and should use LogFileCtx instead of this new OutputJsonCtx.

**Comment by regit** [comment]
OK, if this branch is closed but https://github.com/inliniac/suricata/commit/fd3c1ab6b05d2e0cf296840a95398d581d875c76 needs to get in as it is fixing a real issue. Do you want a PR for that ?

**Pull request closed without merging**
