### PR TITLE
Dev tls cipher suite v7

### PR DESCRIPTION
**Pull request by fooinha**
- Style and code cleanup and review fixes.

- Load list from configuration file (tls.cipher-suites.config) configured at suricata.yaml
   - Fallback to default values if configuration file load is not done.
- Read from comma separated file, ... yaml not done yet.

----

- Allows tls app-layer rules to match TLS handshake cypher suites
Example rules:

```
alert tls any any -> any any
(msg:"SURICATA TLS CIPHER SUITE CLIENT"; 
tls_cipher_suite:client:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,0xcca9;
sid:66666666; 
rev:1;
)
```
```
alert tls any any -> any any 
(msg:"SURICATA TLS CIPHER SUITE SERVER";
tls_cipher_suite:server:0xcca8;
sid:66666667;
rev:1;
)
```

- Custom tls logging for server cypher suite %C 

- Documentation

Replaces #2657 .

fyi, @thus

### CODE REVIEW

**Comment by inliniac** [comment]
@fooinha can you do a rebase to resolve the conflict? @thus can you do a review on the new PR when it's ready?

**Comment by thus** [comment]
@inliniac: sure

**Comment by fooinha** [comment]
Replaced by #2685

**Comment by e-urban** [comment]
Note that the 4 previous commits do not have anything to do with this issue.  I was trying to reference a Redmine issue 2671 instead in my comment, so sorry for the mess.

**Pull request closed without merging**
