### PR TITLE
add json output mode udp stream support.

### PR DESCRIPTION
**Pull request by leightonbao**

### CODE REVIEW

**Comment by inliniac** [comment]
Can you describe the purpose of this change?

**Comment by inliniac** [comment]
QA failure, so closing. Conversation can continue in the closed PR.

**Comment by leightonbao** [comment]
This plugin only use for eve-json mode。At Linux mode，use this plugin log eve-json to Logstash server。Soryy， I can‘not see the QA failure log。So， I do not know what happened（Last Saturday，I can not open the log hyperlink。）。

**Comment by inliniac** [comment]
You can trying following these steps to reproduce the issue:
https://redmine.openinfosecfoundation.org/projects/suricata/wiki/SuriDockerQA

**Pull request closed without merging**
