### PR TITLE
Preview/detect list api/v21

### PR DESCRIPTION
**Pull request by inliniac**
Large patch set to move away from the hardcoded DETECT_SM_LIST_* arrays in the Signature structure. Makes registering new detection lists much easier.

Signature struct goes from ~1100bytes to ~288bytes.

Instead of the large per Signature array of lists, the lists are now part of the inspect engines. Only those inspect engines that apply to a sig are in the sig and so is the list.

### CODE REVIEW

**Comment by inliniac** [comment]
- PR inliniac-pcap: https://buildbot.openinfosecfoundation.org/builders/inliniac-pcap/builds/39
- PR inliniac: https://buildbot.openinfosecfoundation.org/builders/inliniac/builds/547

**Comment by pevma** [comment]
Would a signature struct of about 288 bytes mean that 50k rules loaded by Suri would take about 13.8MB of memory or it is not directly related?

**Comment by inliniac** [comment]
On 14-12-16 22:20, Peter Manev wrote:
> Would a signature struct of about 288 bytes mean that 50k rules loaded
> by Suri would take about 13.8MB of memory or it is not directly related?

No, not directly related. It should use a little bit less memory than
before, but probably negligible vs other detection memory use (e.g.
mpm). I'm hoping for some better cache behavior, but overall this is
about cleaning up the code and improve extensibility.

**Comment by inliniac** [comment]
Replaced by #2473

**Pull request closed without merging**
