### PR TITLE
Prevent panic when malformed rrnames encountered

### PR DESCRIPTION
**Pull request by DominoTree**
Might be a better way to handle this, but this will prevent panics for now

### CODE REVIEW

**Comment by DominoTree** [comment]
We occasionally have malformed DNS traffic cross the wire on our network which cause the Rust implementation to crash.  This patch will drop the malformed `rrname` and allow the software to continue running.

**Comment by jasonish** [comment]
Thanks. I'll have to look at the other unwraps as well.

But I wonder if this should be validated during parsing so an event can be raised? We'd probably still want to log what we can of the DNS message, but perhaps a flag stating malformed name - or log a byte representation of the name?

Thoughts?

**Comment by DominoTree** [comment]
That's not a bad idea, maybe we could just spit out a string with a bunch of hex and prefix it with "MALFORMED" or something - I feel like eve-log would still deal with it properly

**Comment by jasonish** [comment]
@DominoTree Please see this commit https://github.com/inliniac/suricata/pull/2780/commits/19689f5651c4763d38576831b67ba55fa14e56bf which is part of PR https://github.com/inliniac/suricata/pull/2780.

The idea is to print what we can, hex for what we can't...

Not sure if I want to raise a malformed alert for this or not at this time, as the structure of the DNS message was valid if we get to logging.

**Comment by DominoTree** [comment]
@jasonish That looks good to me.  I haven't looked at the RFCs in a while but I'm not sure that it's technically even malformed just because the DNS request can't be converted to valid UTF8.

**Comment by inliniac** [comment]
Fixed in #2781, so closing. Thanks!

**Pull request closed without merging**
