### PR TITLE
Tpacket v3 11

### PR DESCRIPTION
**Pull request by regit**
Update of #2036 

Rebased on latest master and fix message if block size is too small.

PR builds:
- PR regit: https://buildbot.openinfosecfoundation.org/builders/regit/builds/170
- PR regit-pcap: https://buildbot.openinfosecfoundation.org/builders/regit-pcap/builds/166

### CODE REVIEW

**Comment by inliniac** [comment]
On an interface with mtu 9000 block_size 8192 doesn't work:
<pre>
[4380] 3/5/2016 -- 09:19:25 - (source-af-packet.c:1614) <Error> (AFPComputeRingParamsV3) -- [ERRCODE: SC_ERR_INVALID_VALUE(130)] - Block size is too small, it should be at least 9104
</pre>
This makes sense, however I think you said somewhere the block_size for V3 should be a power of 2? If so this warning is inaccurate.

**Comment by regit** [comment]
Do you want an update of text to say "Block size is too small, it should be a power of 2 superior to 9104"

**Comment by inliniac** [comment]
On 03-05-16 09:41, Eric Leblond wrote:
> Do you want an update of text to say "Block size is too small, it should
> be a power of 2 superior to 9104"

Thats the lazy approach. If only we had a computer to actually calculate
the correct value ;)

**Comment by regit** [comment]
Something like:
```
Block size is too small, it should be at least 16384 to contain a frame of length 9088
``` </lazy>

**Comment by inliniac** [comment]
Merged through #2091, thanks Eric!

**Pull request closed without merging**
