### PR TITLE
Threads rename v7 - Bug #1524

### PR DESCRIPTION
**Pull request by zrasmor**
IPS thread names may need a little re-work, but wanted to submit this as a first cut. 
IDS thread names should be pretty consistent with what was decided.

### CODE REVIEW

**Comment by inliniac** [comment]
Finally had some time to look at this, sorry for the delay.

Couple of things I noticed:
- offline (pcap file) modes not yet done
- 'single' doesn't seem to add the iface: "thread "W01" closed on initialization" (when using -i eth0). This should be W01-eth0, right?
- in IPS we use RX/TX in some cases, I think I like RX more than 'C' used in IDS mode elsewhere.
- maybe we can have the names be globally defined instead of hardcoded into all the runmodes, that would make changing it easier.
- Minor: originally I had in mind to use something like 'C#01', adding the #. Thats just cosmetics though.

**Comment by zrasmor** [comment]
Replies to each bullet: 
* Oops, I missed offline pcap mode, i'll add it.
* Yes, this was a question I had - do we want the interface name in every thread name? I adopted whatever the current convention was. I don't believe workers/single appended the interface name previously.
* So I'm clear, are you suggesting that we do away with C completely, replacing it with RX?
* Totally agree about global definitions. Do you have a suggestion for while file to add the definitions to? If not, I can look around and make a suggestion.
* Sure, I can add the '#', that's no problem

**Comment by inliniac** [comment]
* "do we want the interface name in every thread name" -> yeah, where it makes sense. So for workers and single it does, since they are always attached to a iface. The autofp workers are not.

* "do away with C completely, replacing it with RX" -> yeah, but the global defines make it trivial

* "suggestion for while file to add the definitions" -> maybe runmodes.h?

**Comment by inliniac** [comment]
Please close a PR once you've submitted a new one to replace it.

Replaced by #1735

**Pull request closed without merging**
