### PR TITLE
wirefuzz-fix-v2

### PR DESCRIPTION
**Pull request by pevma**
Add a switch to wirefuzz to use asan/lsan options.

### CODE REVIEW

**Comment by inliniac** [comment]
It seems all this does is set an env var? Which leads to the question: why not set it directly?

**Comment by pevma** [comment]
It offers an alternative (as opposed to setting and unsetting globally multiple times) to multiple QA runs combos on different OSs. For example gitlab with docker ( https://hub.docker.com/r/pevma/sqard/tags/ ) while fuzzing and unittesting with different asan options.

**Comment by inliniac** [comment]
Whats the difference between:
ASAN_OPTIONS=detect_leaks=0 wirefuzz.pl ...
and
wirefull.pl -a=ASAN_OPTIONS=detect_leaks=0 ...

**Comment by pevma** [comment]
Not sure if it makes a diff on diff OSs when used in wrapper scripts. Most likely not. I guess I was concentrated on each individual run line.

**Comment by inliniac** [comment]
Not convinced this adds anything, so closing.

Btw, adding a feature and having 'fix' in the PR title is rather confusing. Please use more accurate titles.

**Pull request closed without merging**
