### PR TITLE
Dev feat509 hashing v0.7

### PR DESCRIPTION
**Pull request by serializingme**
New version of the pull request #2059 adding common configurations parsing code. Was rebased to the latest master.

### CODE REVIEW

**Comment by pevma** [comment]
I tested the output and config options - looks good thanks! - 

> "filename":"/menu/en_us/flyout.json","magic":"ASCII text","state":"CLOSED","md5":"fc8e1d17e90f8548742926e8158be75d","sha1":"3eb9c48bfe38fc65f6af0e48c5320539f8779909","sha256":"b3b16afddcec787c532cefe077ac7a87d241919d5e6ceb2e9a04e47259998dc0","stored":false,"size":14480,"tx_id":4}

When I try to to do some sha1/sha256 white/black listing though through loading separate files that contain respectively only MD5/SHA1/SHA256  hashes - only the MD5 ones load. 
For sha1 i get - 

> [22135] 26/5/2016 -- 16:51:28 - (util-detect-file-hash.c:54) <Error> (ReadHashString) -- [ERRCODE: SC_ERR_INVALID_HASH(284)] - /etc/suricata/rules/sha1.sums:45 hash string not 32 characters

For sha256 i get - 

> [22135] 26/5/2016 -- 16:51:28 - (util-detect-file-hash.c:54) <Error> (ReadHashString) -- [ERRCODE: SC_ERR_INVALID_HASH(284)] - /etc/suricata/rules/sha256.sums:45 hash string not 32 characters

For MD5 - it works/loads as expected (previously) as explained here in the wiki - https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Filemd5_and_whiteblack_listing_with_MD5 

I was wondering if this is something that could be easily amended?

**Comment by serializingme** [comment]
I just doubled checked the code, and the error doesn't make sense. Even if you had errors in the checksum files, in the SHA1 related error it should state 40 characters and in the SHA256 it should state 64 characters. This leads me to believe that for some reason the files are being loaded as MD5.

Could you share both files containing the checksums (SHA1 and SHA256) and the rule that is loading them?

**Comment by serializingme** [comment]
I haven't been able to reproduce your error, this is the output I get for each checksum (MD5, SHA1 and SHA256) if I add two lines on each file of a different length that what it should be.

> [11970] 26/5/2016 -- 20:00:54 - (suricata.c:1090) <Notice> (SCPrintVersion) -- This is Suricata version 3.1dev (rev 7c4452f)
> [11970] 26/5/2016 -- 20:00:55 - (util-detect-file-hash.c:54) <Error> (ReadHashString) -- [ERRCODE: SC_ERR_INVALID_HASH(284)] - /usr/local/etc/suricata/rules/md5.txt:7 hash string not 32 characters
> [11970] 26/5/2016 -- 20:00:55 - (util-detect-file-hash.c:54) <Error> (ReadHashString) -- [ERRCODE: SC_ERR_INVALID_HASH(284)] - /usr/local/etc/suricata/rules/md5.txt:8 hash string not 32 characters
> [11970] 26/5/2016 -- 20:00:55 - (util-detect-file-hash.c:54) <Error> (ReadHashString) -- [ERRCODE: SC_ERR_INVALID_HASH(284)] - /usr/local/etc/suricata/rules/sha1.txt:7 hash string not 40 characters
> [11970] 26/5/2016 -- 20:00:55 - (util-detect-file-hash.c:54) <Error> (ReadHashString) -- [ERRCODE: SC_ERR_INVALID_HASH(284)] - /usr/local/etc/suricata/rules/sha1.txt:8 hash string not 40 characters
> [11970] 26/5/2016 -- 20:00:55 - (util-detect-file-hash.c:54) <Error> (ReadHashString) -- [ERRCODE: SC_ERR_INVALID_HASH(284)] - /usr/local/etc/suricata/rules/sha256.txt:7 hash string not 64 characters
> [11970] 26/5/2016 -- 20:00:55 - (util-detect-file-hash.c:54) <Error> (ReadHashString) -- [ERRCODE: SC_ERR_INVALID_HASH(284)] - /usr/local/etc/suricata/rules/sha256.txt:8 hash string not 64 characters

**Comment by serializingme** [comment]
Sorry guys, found a major bug on this version where the detection wasn't working properly. New pull request in #2109.

**Comment by serializingme** [comment]
Sorry guys, found a major bug on this version where the detection wasn't working properly. New pull request in #2109.

**Pull request closed without merging**
