### PR TITLE
Prscript docker v1.5

### PR DESCRIPTION
**Pull request by regit**
Update of #1367 with code rebase and a new commit that clean the command line in docker modes.

PR builds:
- PR regit: https://buildbot.openinfosecfoundation.org/builders/regit/builds/54
- PR regit-pcap: https://buildbot.openinfosecfoundation.org/builders/regit-pcap/builds/52

### CODE REVIEW

**Comment by inliniac** [comment]
Seems the docs at https://github.com/regit/suri-docker-qa are no longer up to date.
$ sudo qa/prscript.py -C master
prscript: error: unrecognized arguments: -C

**Comment by regit** [comment]
Hum, yes doc is not up to date, we don't need the 'master' argument now. But this does not explain the issue.

Regarding the command, do you have python-docker installed ? Do you have it in the list return when doing '-h'.

**Comment by inliniac** [comment]
Yeah this was the problem: I didn't have docker-py installed. When I installed it (0.5.3 for ubuntu 14.04) it works correctly. Maybe you can add a error/warning when ppl try to use the docker commandline opts?

**Comment by regit** [comment]
@inliniac I'm closing this PR and submitting a new one with that inside. PR in progress so it should come fast. The branch is https://github.com/inliniac/suricata/compare/inliniac:master...regit:prscript-docker-v1.7

**Pull request closed without merging**
