### PR TITLE
Napatech counters v2.3

### PR DESCRIPTION
**Pull request by pjyoung1**
Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x ] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x ] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
- Changes to implement packet counters when using Napatech hardware.

### CODE REVIEW

**Comment by inliniac** [comment]
Commits still need cleanup.
1) please prefix the message with 'napatech: '
2) please squash commits like "Changed SCMalloc to SCCalloc" into a previous commit.
3) please make sure the formatting is correct, so not like this https://github.com/inliniac/suricata/pull/2844/commits/62d11159ae9724242a165f240bb42834e21e6355 Commits have a subject that should be no longer than 50 chars (https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Code_Submission_Quality_Criteria#Commits)
4) this should not be part of the commit message 'previous rejected PR's incorporated.' It's not useful as the previous PR is not part of the git history.
5) commit message should reflect this updates the config https://github.com/inliniac/suricata/pull/2844/commits/be57dc0de01f678313c40ba3ac20e784fba3fb7b
6) no need to make these separate commits https://github.com/inliniac/suricata/pull/2844/commits/678cd2dc470a48a25bdbbce4b249a430a914996c https://github.com/inliniac/suricata/pull/2844/commits/9215c640213b0af820df0990c358111ce0dd471d
7) the whole PR is probably best done as a single commit as it's a single logical change?

**Comment by inliniac** [comment]
Also please rebase to the latest master before submitting.

**Comment by psanders240** [comment]
Here is a brief description of the new counters and features added to the Napatech-Suricata integration code: 

**True Zero-Copy mode:** the previous implemented made a copy of each packet.  When "zero-copy: yes" is set in the YAML file, the extra copy step is bypassed to achieve 100% zero-copy

**Host buffer fill level:** Host buffers are buffers in user space that Suricata reads packets from. There is a host buffer for each packet stream. Host buffer size is defined in the ntservice.ini file. The host buffer fill level for will be output to the suricata.log file if the fill level increases over 25%. on a given stream It will then update the current fill level once per second until the buffer fill level returns to 0%. Here is a sample output:

[19785] 26/7/2017 -- 09:02:04 - (util-napatech.c:623) <Info> (NapatechBufMonitorLoop) -- nt1 - Increasing Host Buffer Fill Level :  40%
[19785] 26/7/2017 -- 09:02:15 - (util-napatech.c:630) <Info> (NapatechBufMonitorLoop) -- nt9 - Decreasing Host Buffer Fill Level:    0%

**Packet drop counters:**  Packet and byte drop counters will be updated in the stats.log file now on a per stream basis. Previously the counters were not implemented correctly so they were always stuck at zero. Here is a sample output:

nt0.pkts                                   | Total                     | 19134295
nt0.bytes                                  | Total                     | 8996443041
nt0.drop                                   | Total                     | 0
nt1.pkts                                   | Total                     | 20390888
nt1.bytes                                  | Total                     | 9935749487

**Informational output as Suricata starts up and connects to the Napateech streams:** We now output both the physical CPU core, and NUMA node that a particular worker thread will be executed on. This is usefull for debugging configuration settings to ensure that threads are being run on the correct CPU cores and NUMA node. Sample output:

[3086] 27/6/2017 -- 10:39:20 - (source-napatech.c:239) <Info> (NapatechPacketLoopZC) -- Napatech Pa
cket Loop Started - cpu:   1,    stream:   0 (numa: 0)

**Stream ranges can now be defined in the YAML file**:  Now stream ranges can be defined in the suricata.yaml file to ease configuration when you are running a large number of streams/worker threads. Now you can set "streams: [0-13]" in the YAML file for example.

**Comment by pjyoung1** [comment]
The requested changes have been incorporated (hopefully correctly :-)) into PR "Napatech counters v3.0"

**Comment by inliniac** [comment]
Replaced by #2859

**Pull request closed without merging**
