### PR TITLE
Netmap v1

### PR DESCRIPTION
**Pull request by inliniac**
Implement 'threads: auto' for NETMAP. Tested on FreeBSD 10.3.

Misc other improvements.

@gureedo could you review this?

### CODE REVIEW

**Comment by inliniac** [comment]
- PR inliniac-pcap: https://buildbot.openinfosecfoundation.org/builders/inliniac-pcap/builds/443
- PR inliniac: https://buildbot.openinfosecfoundation.org/builders/inliniac/builds/448

**Comment by gureedo** [comment]
netmap have a bug in linux: NIOCGINFO report invalid values if interface is down.
maybe it's better to get RSS queue count by ethtool ioctls in linux?

**Comment by inliniac** [comment]
So I guess I can first run GetIfaceRSSQueuesNum which returns 0 if the OS is unsupported. Then in the netmap code run NetmapGetRSSCount if GetIfaceRSSQueuesNum returns 0. @gureedo ?

**Comment by inliniac** [comment]
Like this: https://github.com/inliniac/suricata/commit/a8a918545bddf8bbdb449b99cedc73629bdb8294

**Comment by inliniac** [comment]
Replaced by #2133

**Pull request closed without merging**
