### PR TITLE
RFC Rust/nfs/gap/v4

### PR DESCRIPTION
**Pull request by inliniac**
Gap handling for NFS3, not fully complete yet.

@jasonish can you have a look at the approach and let me know what you think?

### CODE REVIEW

**Comment by jasonish** [comment]
The checking for gaps looks fine. I'm curious about what you do on a gap? Looks like the file is truncated? What about leaving holes in files?

**Comment by pevma** [comment]
@jasonish good point.Should it not be the same way we do that for files in http/smtp - so it is homogeneous?

**Comment by inliniac** [comment]
@jasonish yeah I'm truncating as a first step. My initial goal is to allow the parser to continue at all.

@pevma for smtp/http etc we don't do any of this. A gap is fatal and nothing is done beyond that.

**Comment by inliniac** [comment]
Replaced by #2777

**Pull request closed without merging**
