### PR TITLE
dns: add support for sshfp records

### PR DESCRIPTION
**Pull request by inliniac**
Update parser to process the records.

Update json output to log it.

Example record:
```json
{"timestamp":"2015-09-23T15:40:12.141781+0200","flow_id":105716325086112,"pcap_cnt":2,"event_type":"dns","src_ip":"192.168.1.6","src_port":18790,"dest_ip":"192.168.1.1","dest_port":53,"proto":"UDP","dns":{"type":"query","id":45858,"rrname":"rudi.vuurmuur.org","rrtype":"SSHFP","tx_id":0}}
{"timestamp":"2015-09-23T15:40:12.141781+0200","flow_id":105716325086112,"pcap_cnt":2,"event_type":"dns","src_ip":"192.168.1.1","src_port":53,"dest_ip":"192.168.1.6","dest_port":18790,"proto":"UDP","dns":{"type":"answer","id":45858,"rcode":"NOERROR","rrname":"rudi.vuurmuur.org","rrtype":"SSHFP","ttl":30817,"sshfp":{"fingerprint":"51:83:1b:6c:63:9f:f2:94:5d:36:54:89:b6:00:c4:e1:c9:8a:0a:81:61:72:e9:37:d6:8d:af:67:88:44:ae:21","algo":1,"type":2}}}
{"timestamp":"2015-09-23T15:40:12.141781+0200","flow_id":105716325086112,"pcap_cnt":2,"event_type":"dns","src_ip":"192.168.1.1","src_port":53,"dest_ip":"192.168.1.6","dest_port":18790,"proto":"UDP","dns":{"type":"answer","id":45858,"rcode":"NOERROR","rrname":"rudi.vuurmuur.org","rrtype":"SSHFP","ttl":30817,"sshfp":{"fingerprint":"18:e7:54:38:64:67:0d:af:b3:dc:31:59:36:34:3d:2e:f8:95:d0:51","algo":4,"type":1}}}
{"timestamp":"2015-09-23T15:40:12.141781+0200","flow_id":105716325086112,"pcap_cnt":2,"event_type":"dns","src_ip":"192.168.1.1","src_port":53,"dest_ip":"192.168.1.6","dest_port":18790,"proto":"UDP","dns":{"type":"answer","id":45858,"rcode":"NOERROR","rrname":"rudi.vuurmuur.org","rrtype":"SSHFP","ttl":30817,"sshfp":{"fingerprint":"16:a5:36:e9:ee:5b:88:96:98:61:77:d5:1c:89:ab:c1:db:4b:7f:fd","algo":1,"type":1}}}
{"timestamp":"2015-09-23T15:40:12.141781+0200","flow_id":105716325086112,"pcap_cnt":2,"event_type":"dns","src_ip":"192.168.1.1","src_port":53,"dest_ip":"192.168.1.6","dest_port":18790,"proto":"UDP","dns":{"type":"answer","id":45858,"rcode":"NOERROR","rrname":"rudi.vuurmuur.org","rrtype":"SSHFP","ttl":30817,"sshfp":{"fingerprint":"f1:5f:9e:02:8f:04:fc:29:19:28:59:11:69:f2:cc:f2:29:b4:c8:6a:17:81:a7:04:3d:d9:62:1a:5a:fd:9f:c8","algo":4,"type":2}}}
```

Prscript:
- PR inliniac-pcap: https://buildbot.openinfosecfoundation.org/builders/inliniac-pcap/builds/284
- PR inliniac: https://buildbot.openinfosecfoundation.org/builders/inliniac/builds/286

### CODE REVIEW

**Comment by inliniac** [comment]
@regit @jasonish can you review this?

**Comment by jasonish** [comment]
Seems fine.  I take it that a request for the sshfp will only return 0 or 1 records, not multiples like is possible with a txt record - doesn't seem it would make sense to do that anyway.

**Comment by inliniac** [comment]
@jasonish the example above is from a single request/reply. The reply contains 4 records.

**Comment by inliniac** [comment]
https://redmine.openinfosecfoundation.org/issues/1563

**Comment by thus** [comment]
Wouldn't it be cleaner to do like ldns (http://www.nlnetlabs.nl/projects/ldns/) and store all the fields in the answer?

Like this:
```
1 1 16A536E9EE5B8896986177D51C89ABC1DB4B7FFD
<algorithm> <fp_type> <fingerprint>
```

Then you could choose to parse it differently in the various output modules, but DNS traffic with SSHFP type would output sane data by default without having to be told how to parse it.

**Comment by thus** [comment]
This is also the way the "dig" tool prints SSHFP entries.

**Comment by inliniac** [comment]
Not sure I follow what you are suggesting. Could you create a (pseudo) json record based on my example to show what you mean?

**Comment by thus** [comment]
After looking through the code some more, I don't think I agree with myself anymore :p 

My suggestion was to do more parsing of the SSHFP record in app-layer-dns-common.c instead of doing it in the output modules.

I didn't like at first the fact that this is the first rr type where (in the json output) the rdata field is not used to output the answer. But, I realise that this would probably be the case with other types as well, like SOA, LOC, HINFO, and so on.

**Comment by inliniac** [comment]
Seems gcc 4.4 on CentOS managed to produce broken code for the hexstring creation.

**Pull request closed without merging**
