### PR TITLE
 Napatech

### PR DESCRIPTION
**Pull request by psanders240**
Configuration instructions for Napatech capture cards.

### CODE REVIEW

**Comment by inliniac** [comment]
Hi Peter, these instructions should be in the rest format: http://www.sphinx-doc.org/en/stable/rest.html

**Comment by inliniac** [comment]
Please see https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Github_work_flow#Incorporating-feedback and in general https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Code_Submission_Quality_Criteria

Thanks!

**Comment by psanders240** [comment]
After testing some of the instructions that were created using and older Suricata version, they are incorrect. I'll create a new version that has more detail and are fully tested with the current version of Suricata.

**Comment by psanders240** [comment]
Hi Victor,

Add a new pull request for the Napatech documentation.

Let me know what you think.

Thanks,
Pete

**Pull request closed without merging**
