### PR TITLE
app-layer-tls: validity dates from TLS certificate

### PR DESCRIPTION
**Pull request by thus**
Get validity dates (notBefore and notAfter) from TLS certificate.

New detection keywords (tls_notbefore and tls_notafter), added validity dates to extended JSON log and extended TLS log output, and new lua function TlsGetCertValidity().

Changes:
* Added support for human readable date formats (ISO 8601) to rule keywords
* ISO 8601 date (YYYY-mm-ddTHH:MM:SS) in tls-log and output-json-tls.

https://redmine.openinfosecfoundation.org/issues/1583

### CODE REVIEW

**Comment by inliniac** [comment]
Massive QA fail. Unittests:
<pre>
==== TEST RESULTS ====
PASSED: 3841
FAILED: 20
======================
</pre>

**Comment by thus** [comment]
Strange, when I run the unittests, I get:
```
==== TEST RESULTS ====
PASSED: 3878
FAILED: 0
======================
```
Which tests are failing on your end?

**Comment by inliniac** [comment]
See https://s3.amazonaws.com/archive.travis-ci.org/jobs/87438588/log.txt

**Comment by thus** [comment]
It's still strange that none of the tests fail on my test machine.

It looks like the tests failing, are the tests I created for testing the parsing of ISO 8601 time strings. They all fail, while the tests checking Unix time strings does not, even though they use the same function for parsing the date.

Any ideas of why this happen, or hints on where I should start looking to fix this? :)

**Comment by thus** [comment]
I managed to reproduce the failed tests using a machine with a 3.6 kernel, so disregard my last question :)

**Comment by thus** [comment]
\*facepalm\*

This error was because of my use of "mktime". I didn't realize that it use the time zone from the executing environment, instead of using "tm_gmtoff". Because of this, it worked on one machine, but failed on another machine with different time zone settings.

I'll fix this and send a new pull release :)

**Comment by inliniac** [comment]
Ah, good catch. Time handling is definitely non-trivial...

**Comment by thus** [comment]
This pull request is replaced by #1722.

**Pull request closed without merging**
