### PR TITLE
doc: make sphinx generated documentation available at suricata dist.

### PR DESCRIPTION
**Pull request by fooinha**
Make sphinx generated documentation available at suricata dist.

Install userguide at docdir and in suricata dist.

```
make clean distcheck...
if test -d "suricata-3.2dev"; then find "suricata-3.2dev" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "suricata-3.2dev" || { sleep 5 && rm -rf "suricata-3.2dev"; }; else :; fi
=================================================
suricata-3.2dev archives ready for distribution:
suricata-3.2dev.tar.gz
=================================================
 ```

### CODE REVIEW

**Comment by inliniac** [comment]
@jasonish can you have a look?

**Comment by jasonish** [comment]
I don't quite get it. This appears to apply DESTDIR at build time, but I thought that variable was mostly used to stage an install in some fakeroot for packaging, but not usually take affect during the build.

Can you tell me what use case fails without this?

**Comment by jasonish** [comment]
Fails make distcheck:

```
ERROR: files left after uninstall:
  (check DESTDIR support)
./_build/doctrees/environment.pickle
./_build/doctrees/what-is-suricata.doctree
./_build/doctrees/setting-up-ipsinline-for-linux.doctree
./_build/doctrees/rules/tls-keywords.doctree
./_build/doctrees/rules/thresholding.doctree
./_build/doctrees/rules/snort-compatibility.doctree
./_build/doctrees/rules/rule-lua-scripting.doctree
./_build/doctrees/rules/prefilter.doctree
./_build/doctrees/rules/pcre.doctree
./_build/doctrees/rules/payload-keywords.doctree
./_build/doctrees/rules/normalized-buffers.doctree
./_build/doctrees/rules/modbus-keyword.doctree
./_build/doctrees/rules/meta.doctree
./_build/doctrees/rules/live-rule-swap.doctree
./_build/doctrees/rules/intro.doctree
./_build/doctrees/rules/index.doctree
./_build/doctrees/rules/http-uri-normalization.doctree
./_build/doctrees/rules/http-keywords.doctree
./_build/doctrees/rules/header-keywords.doctree
./_build/doctrees/rules/flowint.doctree
./_build/doctrees/rules/flow-keywords.doctree
./_build/doctrees/rules/file-keywords.doctree
./_build/doctrees/rules/fast-pattern-explained.doctree
./_build/doctrees/rules/fast-pattern.doctree
./_build/doctrees/rules/enip-keyword.doctree
./_build/doctrees/rules/dns-keywords.doctree
./_build/doctrees/rules/dnp3-keywords.doctree
./_build/doctrees/rules/adding-your-own-rules.doctree
./_build/doctrees/reputation/ipreputation/ip-reputation-rules.doctree
./_build/doctrees/reputation/ipreputation/ip-reputation-format.doctree
./_build/doctrees/reputation/ipreputation/ip-reputation-config.doctree
./_build/doctrees/reputation/ipreputation/ip-reputation.doctree
./_build/doctrees/reputation/index.doctree
./_build/doctrees/public-data-sets.doctree
./_build/doctrees/performance/tuning-considerations.doctree
./_build/doctrees/performance/tcmalloc.doctree
./_build/doctrees/performance/statistics.doctree
./_build/doctrees/performance/runmodes.doctree
./_build/doctrees/performance/rule-profiling.doctree
./_build/doctrees/performance/packet-profiling.doctree
./_build/doctrees/performance/packet-capture.doctree
./_build/doctrees/performance/index.doctree
./_build/doctrees/performance/ignoring-traffic.doctree
./_build/doctrees/performance/hyperscan.doctree
./_build/doctrees/performance/high-performance-config.doctree
./_build/doctrees/output/syslog-alerting-comp.doctree
./_build/doctrees/output/lua-output.doctree
./_build/doctrees/output/index.doctree
./_build/doctrees/output/eve/index.doctree
./_build/doctrees/output/eve/eve-json-output.doctree
./_build/doctrees/output/eve/eve-json-format.doctree
./_build/doctrees/output/eve/eve-json-examplesjq.doctree
./_build/doctrees/output/custom-http-logging.doctree
./_build/doctrees/oinkmaster.doctree
./_build/doctrees/manpages/suricata.doctree
./_build/doctrees/manpages/index.doctree
./_build/doctrees/make-sense-alerts.doctree
./_build/doctrees/licenses/index.doctree
./_build/doctrees/licenses/gnu-gpl-v2.0.doctree
./_build/doctrees/licenses/cc-nc-4.0.doctree
./_build/doctrees/initscripts.doctree
./_build/doctrees/index.doctree
./_build/doctrees/file-extraction/public-sha1-md5-data-sets.doctree
./_build/doctrees/file-extraction/md5.doctree
./_build/doctrees/file-extraction/file-extraction.doctree
./_build/doctrees/configuration/suricata-yaml.doctree
./_build/doctrees/configuration/snort-to-suricata.doctree
./_build/doctrees/configuration/multi-tenant.doctree
./_build/doctrees/configuration/log-rotation.doctree
./_build/doctrees/configuration/index.doctree
./_build/doctrees/configuration/global-thresholds.doctree
./_build/doctrees/configuration/dropping-privileges.doctree
./_build/doctrees/command-line-options.doctree
./_build/doctrees/capture-hardware/myricom.doctree
./_build/doctrees/capture-hardware/index.doctree
./_build/doctrees/capture-hardware/endace-dag.doctree
./_build/doctrees/acknowledgements.doctree
./_build/man/suricata.1
Makefile:739: recipe for target 'distuninstallcheck' failed
make[1]: *** [distuninstallcheck] Error 1
make[1]: Leaving directory '/home/jason/projects/oisf/suricata/suricata-3.2dev/_build/sub'
Makefile:683: recipe for target 'distcheck' failed
make: *** [distcheck] Error 1
```

**Comment by fooinha** [comment]
@jasonish , yes, this was nonsense. I changed so installs userguide in docdir and make it available at dist tarball.

Side effects of using to many building tools/systems.
I needed a refresh with autotools.

Thanx.

**Comment by fooinha** [comment]
Sorry, @inliniac, the real goal of this PR was to include the html userguide in installation.
If we don't want to distribute it, then keep this closed.

Otherwise consider, to re-open or review this, as the changes I made yesterday, do install userguide in a better way.
I also changed the PR title.

**Comment by inliniac** [comment]
On 06-10-16 13:57, fooinha wrote:
> Sorry, @inliniac <https://github.com/inliniac>, the real goal of this PR
> was to include the html userguide in installation.
> If we don't want to distribute it, then keep this closed.
> 
> Otherwise consider, to re-open or review this, as the changes I made
> yesterday, do install userguide in a better way.
> I also changed the PR title.

I closed it because Jason said it was broken. You'll have to submit a
new PR if you want the changes to be considered.

**Pull request closed without merging**
