### PR TITLE
Redisdead v1.15

### PR DESCRIPTION
**Pull request by regit**
Update of PR #1681 with addressed comments. One incremental patch for one of them as it was an optimization and getting it in a previous patch was painful.

PR builds:
- PR regit: https://buildbot.openinfosecfoundation.org/builders/regit/builds/107
- PR regit-pcap: https://buildbot.openinfosecfoundation.org/builders/regit-pcap/builds/105

### CODE REVIEW

**Comment by inliniac** [comment]
Merged through #1712, thanks Eric. Can you make sure there is a feature ticket for this as well?

**Comment by regit** [comment]
TIcket created https://redmine.openinfosecfoundation.org/issues/1582 Tell me if you want more info in the ticket.

**Comment by inliniac** [comment]
A link to this PR and it can be closed, thanks!

**Comment by regit** [comment]
Done.

**Pull request closed without merging**
