### PR TITLE
unix socket stats v5

### PR DESCRIPTION
**Pull request by inliniac**
As #1861, fixing:
- disable unix socket was broken
- clean up jansson includes

Prscript:
- PR inliniac-pcap: https://buildbot.openinfosecfoundation.org/builders/inliniac-pcap/builds/352
- PR inliniac: https://buildbot.openinfosecfoundation.org/builders/inliniac/builds/355

### CODE REVIEW

**Comment by inliniac** [comment]
@regit I intend to merge this soon, any feedback?

**Comment by regit** [comment]
@inliniac small review done. Really minor comments.

**Comment by inliniac** [comment]
Thanks Eric. I fixed the typos.

**Comment by duanehoward** [comment]
Sorry for the delay on this, I'm starting to poke around a bit, it seems like everything in the threads:Global section is just a subset of everything I see above (basically just the memuse subset?) Is this intentional? It seems like the "Global" section under threads could just be dropped?

Example below
{
    "message": {
        <snip>
        "flow": {
            <snip>
            "memuse": **2185382688**,
            "spare": 3993699
        },
        "tcp": {
            <snip>
            "memuse": **4284768**,
            "segment_memcap_drop": 0,
            <snip>
        },
        <snip>
        "threads": {
            "Global": {
                "flow": {
                    "memuse": **2185382688**
                },
                "http": {
                    "memcap": 0,
                    "memuse": 55718054
                },
                "dns": {
                    "memcap_global": 0,
                    "memcap_state": 0,
                    "memuse": 6088819
                },
                "tcp": {
                    "reassembly_memuse": 167709784,
                    "memuse": **4284768**
                }
            },

**Comment by inliniac** [comment]
This has been merged with minor fixes through #1868

**Comment by inliniac** [comment]
@duanehoward this is a side effect of using the Eve record. As in Eve it's configurable to log totals only, threads only, or both, the 'global' counters are added to both.

**Comment by duanehoward** [comment]
That's cool. I just wanted to check =)

**Pull request closed without merging**
