### PR TITLE
Next/20170127/v5

### PR DESCRIPTION
**Pull request by inliniac**
#2522, #2520 and improvements for stream segment pool sizes.

Prscript:
- PR inliniac-pcap: https://buildbot.openinfosecfoundation.org/builders/inliniac-pcap/builds/60
- PR inliniac: https://buildbot.openinfosecfoundation.org/builders/inliniac/builds/568

### CODE REVIEW

**Comment by pevma** [comment]
I have a reproducible segfault  - right a few seconds after starting - 

> Core was generated by `/usr/local/bin/suricata -c /etc/suricata/suricata.yaml --af-packet=eth1 -vvv -D'.
> Program terminated with signal 11, Segmentation fault.
> #0  0x000000000060126f in FlowVarPrint (gv=0x60903f) at flow-var.c:147
> 147	            SCLogDebug("Name idx \"%" PRIu16 "\", Value \"", fv->idx);
> Thread 23 (LWP 3670):
> #0  0x00007f8e12f2f06d in ?? ()
> #1  0x0000000000000000 in ?? ()
> 
> Thread 22 (LWP 3610):
> #0  0x00007f8e12f2f06d in ?? ()
> #1  0x0000000000000000 in ?? ()
> ...
> ...
> Thread 1 (LWP 31819):
> #0  0x000000000060126f in FlowVarPrint (gv=0x60903f) at flow-var.c:147
> #1  0x0000000000602180 in FlowWorker (tv=0x17796c0, p=0x1734d1e0, data=0x60903f, preq=0x16dead40, unused=0x16dead40) at flow-worker.c:201
> #2  0x00000000005f28c0 in DetectXbitParse (de_ctx=0x600f49, rawstr=0x7fff1e1b0b10 "0\v\033\036\377\177", cdout=0x0) at detect-xbits.c:303
> #3  0x00007f8e12e917ed in ?? ()
> #4  0x0000000000000000 in ?? ()
> (gdb)

**Comment by inliniac** [comment]
@pevma please provide more info about how to reproduce or send a test case. Thanks.

**Comment by pevma** [comment]
Actually it is easy to reproduce for me but wondering how to get you pcap/or reproducible case.

So this is a light (1Gbps) a bit old traffic box (Trusty with 3.13 kernel). My command line - 
> /opt/bin/suricata -c /opt/suricata.yaml -l /opt/log/ --set="af-packet.0.interface=eth1" -vvv --af-packet
using the default suricata.yaml (so no changes) and it segfaults right after start (maybe not related to traffic at all). 
Please see another case attached:
[gdb.txt](https://github.com/inliniac/suricata/files/737181/gdb.txt)

**Comment by inliniac** [comment]
Issue should be fixed in #2524

**Pull request closed without merging**
