### PR TITLE
TPACKET_V3 fixes v2

### PR DESCRIPTION
**Pull request by gozzy**
Splitted #2574.

### CODE REVIEW

**Comment by gozzy** [comment]
@regit, should be better now.
@inliniac, should I create a ticket for this?

**Comment by inliniac** [comment]
Yeah please do. Also, the commit message formatting could use a bit of refinement :)

**Comment by regit** [comment]
On commit message: please just prefix with 'af-packet'

**Comment by regit** [comment]
That's far better. Really easier to read now.

**Pull request closed without merging**
