### PR TITLE
eve-log: ZeroMQ eve-log output support.

### PR DESCRIPTION
**Pull request by decanio**
Add the ability to send eve-log output to ZeroMQ
- PR decanio: https://buildbot.openinfosecfoundation.org/builders/decanio/builds/17
- PR decanio-pcap: https://buildbot.openinfosecfoundation.org/builders/decanio-pcap/builds/17

### CODE REVIEW

**Comment by inliniac** [comment]
It is my understanding that ZeroMQ's license is currently not compatible with ours. They used LGPLv3, we GPLv2.

However, they indent to move to MPLv2: http://zeromq.org/area:licensing

**Comment by zrasmor** [comment]
@inliniac I have done some similar prototyping to integrate czmq (http://czmq.zeromq.org/) into Suricata to export files for scanning with LaikaBoss (https://github.com/lmco/laikaboss). The czmq bindings are MPL v2 - does this alleviate the license incompatibility issue?

**Comment by inliniac** [comment]
Not sure if that works. It seems the core license also uses an exception of some kind. IANAL so I prefer waiting for their MIT relicense :)

**Comment by inliniac** [comment]
GPLv2 compatibility with MPLv2 might work: https://www.gnu.org/licenses/license-list.html#MPL-2.0
Although I'm a bit confused about the part about “Incompatible With Secondary Licenses.”

**Pull request closed without merging**
