### PR TITLE
TLS logging for session resumption 1.3

### PR DESCRIPTION
**Pull request by rtkrruvinskiy**
We assume session resumption has occurred if the Client Hello message included
a session id, we have not seen the server certificate, but we have seen a
Change Cipher Spec message from the server.

Previously, these transactions were not logged at all because the server cert
was never seen.

https://redmine.openinfosecfoundation.org/issues/1969

Replaces https://github.com/inliniac/suricata/pull/2555

### CODE REVIEW

**Comment by inliniac** [comment]
@thus I'll consider this once you sign off on it

**Comment by thus** [comment]
Prscript:
- PR thus-pcap: https://buildbot.openinfosecfoundation.org/builders/thus-pcap/builds/105
- PR thus: https://buildbot.openinfosecfoundation.org/builders/thus/builds/105

**Comment by thus** [comment]
@inliniac: It looks good to me.

**Comment by inliniac** [comment]
I missed this previously: as a EVE option is added we'll need an update to the docs as well.

**Comment by inliniac** [comment]
https://github.com/inliniac/suricata/blob/master/doc/userguide/output/eve/eve-json-format.rst should be updated, but it should probably wait until https://github.com/inliniac/suricata/pull/2568/files#diff-7823d9d82df45a9858e8925a6259022e is merged (or a newer version of it)

**Comment by inliniac** [comment]
https://github.com/inliniac/suricata/blob/master/doc/userguide/configuration/suricata-yaml.rst#eve-extensible-event-format as well

**Comment by rtkrruvinskiy** [comment]
@inliniac To clarify, should I resubmit this PR with the requested doc updates?

**Comment by inliniac** [comment]
On 20-02-17 19:26, Ray Ruvinskiy wrote:
> @inliniac <https://github.com/inliniac> To clarify, should I resubmit
> this PR with the requested doc updates?

Yes please! Thanks!

**Comment by rtkrruvinskiy** [comment]
Per your suggestion, I'll resubmit after https://github.com/inliniac/suricata/pull/2580 or its successor is merged. Thanks!

**Comment by rtkrruvinskiy** [comment]
Replaced by https://github.com/inliniac/suricata/pull/2602

**Pull request closed without merging**
