### PR TITLE
TCP reassembly buffer v184.8

### PR DESCRIPTION
**Pull request by inliniac**
Rebase of #2645, plus some small adjustments.

Prscript:
- PR inliniac-pcap: https://buildbot.openinfosecfoundation.org/builders/inliniac-pcap/builds/89
- PR inliniac: https://buildbot.openinfosecfoundation.org/builders/inliniac/builds/597

### CODE REVIEW

**Comment by pevma** [comment]
After some live runs I noticed (running on the same machine/traffic/config):  
- that with this PR (as opposed to master) Suri enters emergency mode now and then. ()where as usually never happens with master)
- that i have more drops and reassembly gaps 
than the usual/master stats.

Will continue to investigate...

**Comment by gozzy** [comment]
@pevma, it looks strange - on our [inline mode] tests with IXIA this version behaved better that the one from master branch (AFAIR, there were no memcap drops or reassembly gaps in stats.log). Probably it's related to reassembly.segment-prealloc parameter, but I am not sure about that. Anyway, your tests differ from ours and obviously may give different results.

**Comment by inliniac** [comment]
In IPS mode a bigger improvement is expected due to some changes in how it works.

**Comment by inliniac** [comment]
Merged through #2673

**Pull request closed without merging**
