### PR TITLE
mpm ac-ks v11

### PR DESCRIPTION
**Pull request by inliniac**
Port of the mpm ac-tile by @ken-tilera to other platforms. Named it 'ac-ks' => Kenneth Steele.

Prscript:
- PR inliniac-pcap: https://buildbot.openinfosecfoundation.org/builders/inliniac-pcap/builds/288
- PR inliniac: https://buildbot.openinfosecfoundation.org/builders/inliniac/builds/290

### CODE REVIEW

**Comment by inliniac** [comment]
@pevma can you test this for perf? Seeing promising results in pcap tests, less so in replay tests.

**Comment by pevma** [comment]
I have started a perf-test sequence on live traffic.

It seems there are some troubles in general with live rule reloads that i am also looking into - however much more vivid when employing this mpm algorithm. It will not execute any additional reload after the first (USR2) reload in  a short sequence.

**Comment by pevma** [comment]
Observations after running for some time:
- live rule reload is a problem as previously explained
- pf-ring performance is steady/the same
- af-packet performance is improved

**Comment by inliniac** [comment]
Replaced by #1697

**Pull request closed without merging**
