### PR TITLE
DNP3 Support - v13

### PR DESCRIPTION
**Pull request by jasonish**
Previous PR: #2288 

Changes from last PR:
- Rebased with new detection registration.
- Fixups commits squashed into previous commits.

Redmine ticket:
https://redmine.openinfosecfoundation.org/issues/1745

This PR contains:
* An application decoder for DNP3.
* Snort compatible DNP3 keywords:
  * dnp3_data
  * dnp3_func
  * dnp3_ind
  * dnp3_obj
* A DNP3 output module for EVE (JSON logging).
* DNP3 support for Lua detection.

Documentation for the DNP3 rule keywords can be found here:
https://redmine.openinfosecfoundation.org/projects/suricata/wiki/DNP3_keyword
OR in newer format:
http://jasonish-suricata.readthedocs.org/en/latest/rules/dnp3-keywords.html

Prscript:
- PR jasonish-pcap: https://buildbot.openinfosecfoundation.org/builders/jasonish-pcap/builds/2
- PR jasonish: https://buildbot.openinfosecfoundation.org/builders/jasonish/builds/352

### CODE REVIEW

**Comment by inliniac** [comment]
Breaks if jansson isn't installed:
<pre>
In file included from output.c:72:0:
output-json-dnp3.h:23:1: error: unknown type name 'json_t'
 json_t *JsonDNP3LogRequest(DNP3Transaction *);
 ^
output-json-dnp3.h:24:1: error: unknown type name 'json_t'
 json_t *JsonDNP3LogResponse(DNP3Transaction *);
 ^
Makefile:1581: recipe for target 'output.o' failed
</pre>

**Comment by inliniac** [comment]
CentOS6 doesn't like something:
<pre>
cc1: warnings being treated as errors
app-layer-dnp3-objects.c: In function ‘DNP3DecodeObjectG12V3’:
app-layer-dnp3-objects.c:113: error: dereferencing pointer ‘out.46’ does break strict-aliasing rules
app-layer-dnp3-objects.c:286: note: initialized from here
</pre>

**Comment by jasonish** [comment]
Ok, fixed.  Thanks.

**Comment by jasonish** [comment]
Whats your ./configure look like?  I've tried CentOS 6.6 and 6.8, both with
gcc 4.4.7 and do not get this error.  Thanks.

**Comment by inliniac** [comment]
On 02-10-16 17:14, Jason Ish wrote:
> Whats your ./configure look like? I've tried CentOS 6.6 and 6.8, both with
> gcc 4.4.7 and do not get this error. Thanks.

Doesn't look special:

 argv: ['./configure', '--disable-coccinelle']
 environment:
  CFLAGS=-O3 -Wall -Wextra -Werror -Wno-unused-parameter
-Wno-unused-function

**Comment by jasonish** [comment]
On Sun, Oct 2, 2016 at 10:07 AM, Victor Julien <notifications@github.com>
wrote:

> On 02-10-16 17:14, Jason Ish wrote:
> > Whats your ./configure look like? I've tried CentOS 6.6 and 6.8, both
> with
> > gcc 4.4.7 and do not get this error. Thanks.
>
> Doesn't look special:
>
> argv: ['./configure', '--disable-coccinelle']
> environment:
> CFLAGS=-O3 -Wall -Wextra -Werror -Wno-unused-parameter
> -Wno-unused-function


Thanks. Its the -O3.  It compiles fine at -Os and -O2. Will investigate.

**Comment by inliniac** [comment]
Btw give scan-build a run as well. This branch introduces some new warnings. Some are the TAILQ fp's, but there are a few more.

**Pull request closed without merging**
