### PR TITLE
rust: core integration - v6

### PR DESCRIPTION
**Pull request by jasonish**
Previous PR: #2670 

Changes from last PR:
- libjansson wrapper
- Rust must be explicitly enabled.

Prscript:
- PR jasonish-pcap: https://buildbot.openinfosecfoundation.org/builders/jasonish-pcap/builds/134
- PR jasonish: https://buildbot.openinfosecfoundation.org/builders/jasonish/builds/486

### CODE REVIEW

**Comment by inliniac** [comment]
So the proposed file layout is:


rust/
rust/src/*.rs <- common files
rust/src/dns/*.rs <- dns app layer
rust/src/_applayer_/*.rs other app layer

I thought before you wanted to do a flat file layout, but maybe I misunderstood that.

**Comment by inliniac** [comment]
I'm not yet convinced the exposing of the libjansson api like this is the best idea. I'd like to minimize the use of C api's form the Rust side of things.

I wonder if an approach like the data store in https://github.com/inliniac/suricata/pull/2538 that can be used from C makes for a cleaner boundary. The logger would then live in C however.

Another way I guess would be to fully construct a JSON/log message in rust, and only call LogFileCtx::Write from Rust on that message.

**Comment by jasonish** [comment]
> I'm not yet convinced the exposing of the libjansson api like this is the best idea. I'd like to minimize the use of C api's form the Rust side of things.

To be honest, this is where Rust's FFI excels, calling into C.

> 
> I wonder if an approach like the data store in #2538 that can be used from C makes for a cleaner boundary. The logger would then live in C however.

It hasn't clicked with me how that would work with DNS without making it more complex. Also, if the logging was going to be done from C, to be honest, its almost easier to do the decoding in C.  The more bridge code there, the less valuable using Rust becomes I think.

> 
> Another way I guess would be to fully construct a JSON/log message in rust, and only call LogFileCtx::Write from Rust on that message.

This would be an OK option, some code duplication in logging but lets the Rust log stuff that is decoded in Rust, etc.

I've taken the same approach with Lua, by passing the Lua state into Rust.  IMO its so much cleaner, simpler, than defining data stores for passing data back (again, opinions may vary here). Probably easier to teach as well when it comes to training as its using familiar APIs from the C side already.

**Comment by jasonish** [comment]
> So the proposed file layout is:
> 
> rust/
> rust/src/.rs <- common files
> rust/src/dns/.rs <- dns app layer
> rust/src/applayer/*.rs other app layer
> 
> I thought before you wanted to do a flat file layout, but maybe I misunderstood that.

No, not a flat file layout, but a single crate with modules. I wasn't keen on the multi-create layout. 

So given the above, the "common" files is the top module, or core module. Might make sense to move that one level down? Common, core, or whatever? Then you have the DNS module, and so on.

**Comment by jasonish** [comment]
Out of date. The DNS branch contains this branch in its earlier commits. See:
https://github.com/inliniac/suricata/pull/2708

**Pull request closed without merging**
