### PR TITLE
DNP3 Support - v22.3

### PR DESCRIPTION
**Pull request by jasonish**
Previous PR: #2350 

Changes from last PR:
- Fix PPC compile issue (untested)
- Fix CentOS 5 compile issue - required refactoring of the floating point extraction code (https://github.com/jasonish/suricata/blob/dev-dnp3-v22.2-rebased/src/app-layer-dnp3-objects.c#L248)
- Removed notice logging.
- Fix bool return in DNP3HasEvents()
- Remove extra AppLayerDecoderEventsFreeEvents(&tx->decoder_events)
- Fix style issue with opening braces.
- Remove stale TODO comment.
- Use explicit types in detect-dnp3 parsing code; use existing string to integer conversion functions.
- Merge detect-engine-dnp3 into detect-dnp3.
- Move struct DetectDNP into detect-dnp3.c.
- Use a common JsonDNP3PrefixIsSize function.
- Remove output registration logging when no json support.
- Fix unit tests on OpenBSD (double mutex unlock)
- Cleanup func, iin, and obj registration as the list only needs to be registered once.

The diff prior to the rebase can be seen here:
https://gist.github.com/jasonish/6640aee31c7506330499803eb06fb69b

Mpm comment (https://github.com/inliniac/suricata/pull/2350#discussion_r84067158) has not been addressed.

This PR contains:
* An application decoder for DNP3.
* Snort compatible DNP3 keywords:
  * dnp3_data
  * dnp3_func
  * dnp3_ind
  * dnp3_obj
* A DNP3 output module for EVE (JSON logging).
* DNP3 support for Lua detection.

Documentation for the DNP3 rule keywords can be found here:
http://suricata.readthedocs.io/en/latest/rules/dnp3-keywords.html

Prscript:
- PR jasonish-pcap: https://buildbot.openinfosecfoundation.org/builders/jasonish-pcap/builds/27
- PR jasonish: https://buildbot.openinfosecfoundation.org/builders/jasonish/builds/377

### CODE REVIEW

**Comment by inliniac** [comment]
CentOS5 again:
<pre>
if gcc -DHAVE_CONFIG_H -I. -I. -I..   -I./../libhtp/   -Wextra -Werror-implicit-function-declaration -fno-tree-pre    -Wall -Wno-unused-parameter -std=gnu99 -DLOCAL_STATE_DIR=\"/usr/local/var\"  -O0 -Wall -Wextra -Werror -Wno-unused-parameter -MT app-layer-dnp3-objects.o -MD -MP -MF ".deps/app-layer-dnp3-objects.Tpo" -c -o app-layer-dnp3-objects.o app-layer-dnp3-objects.c; \
	then mv -f ".deps/app-layer-dnp3-objects.Tpo" ".deps/app-layer-dnp3-objects.Po"; else rm -f ".deps/app-layer-dnp3-objects.Tpo"; exit 1; fi
cc1: warnings being treated as errors
app-layer-dnp3-objects.c:225: warning: ‘DNP3ReadUint64’ defined but not used
make[3]: Leaving directory `/home/victor/qa/buildbot/donkey/C5_build/Private/src'
make[3]: *** [app-layer-dnp3-objects.o] Error 1
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/victor/qa/buildbot/donkey/C5_build/Private/src'
make[1]: Leaving directory `/home/victor/qa/buildbot/donkey/C5_build/Private'
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
</pre>

**Comment by inliniac** [comment]
Actually not just CentOS. This is Ubuntu 16.04:
<pre>
app-layer-dnp3-objects.c:224:12: error: unused function 'DNP3ReadUint64' [-Werror,-Wunused-function]
static int DNP3ReadUint64(const uint8_t **buf, uint32_t *len, uint64_t *out)
           ^
1 error generated.
</pre>

**Comment by inliniac** [comment]
Killed my QA run as many builders failed with this same issue.

**Comment by jasonish** [comment]
Should prscript have picked this up?

**Comment by jasonish** [comment]
Oops, yeah.. That is not used now with the newer float 64 decoding.

**Pull request closed without merging**
