### PR TITLE
eve: check redis reply in non pipeline mode

### PR DESCRIPTION
**Pull request by fooinha**
We may lose the reply if disconnection happens.
Reconnection is needed.

Different commit as @regit suggested.

Better commit message.

Thanx

### CODE REVIEW

**Comment by inliniac** [comment]
@regit can you test the scenario this patch addresses?

**Comment by fooinha** [comment]
should i create a redmine ticket for this ?

**Comment by inliniac** [comment]
On 26-10-16 13:25, fooinha wrote:
> should i create a redmine ticket for this ?

Please do! Thanks!

**Comment by fooinha** [comment]
https://redmine.openinfosecfoundation.org/issues/1935

**Comment by regit** [comment]
@inliniac tested with success, good fix.

**Comment by inliniac** [comment]
Merged through #2391, thanks @fooinha! Also thanks @regit for testing and review!

**Pull request closed without merging**
