### PR TITLE
unix socket stats v0

### PR DESCRIPTION
**Pull request by inliniac**
Attempt at getting a new dump-counters working. Feedback welcome.

### CODE REVIEW

**Comment by inliniac** [comment]
@regit any feedback?

**Comment by inliniac** [comment]
- PR inliniac-pcap: https://buildbot.openinfosecfoundation.org/builders/inliniac-pcap/builds/349
- PR inliniac: https://buildbot.openinfosecfoundation.org/builders/inliniac/builds/352

**Comment by regit** [comment]
Looks good to me with a small comment on a commit.

**Comment by inliniac** [comment]
Replaced by #1859

**Pull request closed without merging**
