### PR TITLE
1.  The enip-feature-1495-v4 branch contains support for the ENIP/CIP

### PR DESCRIPTION
**Pull request by kwong-solana**
1.  The enip-feature-1495-v4 branch contains support for the ENIP/CIP
Industrial protocol
2. This is an app layer implementation which uses the "enip" protocol
and "cip_service" and "enip_command" keywords
3.  Rebased master to clean out commits done on master and then 
merged to latest code
4.  Addresses failed PR's https://github.com/inliniac/suricata/pull/1810 
and https://github.com/inliniac/suricata/pull/1819

### CODE REVIEW

**Comment by inliniac** [comment]
Can you provide some test cases? Pcap + rules that need to match and how often? I can then setup some automated testing for that.

Also: this will need AFL entry points similar to https://github.com/inliniac/suricata/pull/1999/files#diff-f5e72d82198f985531c162cd7fca0b54R1430 Then we'll hammer it with some fuzz testing.

**Comment by inliniac** [comment]
Plus we need a rebase to the current git master.

**Comment by inliniac** [comment]
Thanks!

**Comment by kwong-solana** [comment]
Hi Victor,

I will try to dig up some pcaps that don't break any of our disclosure 
agreements.

Will I need to make a new branch like before when rebasing and adding 
the requested AFL?

How soon do you need this so that we can make the next release?

Thanks,

Kevin

On 13/04/2016 10:47 AM, Victor Julien wrote:
>
> Can you provide some test cases? Pcap + rules that need to match and 
> how often? I can then setup some automated testing for that.
>
> Also: this will need AFL entry points similar to 
> https://github.com/inliniac/suricata/pull/1999/files#diff-f5e72d82198f985531c162cd7fca0b54R1430 
> Then we'll hammer it with some fuzz testing.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/inliniac/suricata/pull/1827#issuecomment-209484094>
>

-- 
Kevin Wong

Solana Networks Inc | 613.596.2557 x575 | kwong@solananetworks.com
  
http://www.solananetworks.com

http://www.sparrowiq.com

**Pull request closed without merging**
