### PR TITLE
pfring v0.6: implements ips mode

### PR DESCRIPTION
**Pull request by glongo**
This PR permits to use suricata and PF_RING in ips mode,
it addresses comments in the previous PR.

Last PR: https://github.com/inliniac/suricata/pull/1288

- PR build: https://buildbot.openinfosecfoundation.org/builders/glongo/builds/21
- PR pcaps: https://buildbot.openinfosecfoundation.org/builders/glongo-pcap/builds/20

### CODE REVIEW

**Comment by gozzy** [comment]
A small question: should LRO/GRO be turned off? For instance, AF_PACKET can't handle offloading - transfer size exceeds 65k and an error occurs.

**Comment by glongo** [comment]
@gozzy it's better to turn off LRO/GRO.
Btw could be a good idea to print a warning message, as for AF_PACKET.

**Comment by inliniac** [comment]
It seems that it is critical to load the pf_ring module with:
modprobe pf_ring enable_tx_capture=0

Without that traffic didn't forward for me.

**Comment by inliniac** [comment]
Regarding that last comment, can that be checked at Suricata startup?

**Comment by inliniac** [comment]
In my testing I haven't been able to get this to work at any reasonable speed. Also latency was huge.

**Pull request closed without merging**
