### PR TITLE
[preview] detect grouping v167

### PR DESCRIPTION
**Pull request by inliniac**
Changes since #1725:
* rebase to master
* instead of global single/full setting, allow for per buffer type shared/unique

Prscript:
- PR inliniac-pcap: https://buildbot.openinfosecfoundation.org/builders/inliniac-pcap/builds/306
- PR inliniac: https://buildbot.openinfosecfoundation.org/builders/inliniac/builds/308

### CODE REVIEW

**Comment by pevma** [comment]
I dont see the suricata.yaml.in changes with regards to  - "instead of global single/full setting, allow for per buffer type shared/unique" or that is not yet available in the config?

**Comment by pevma** [comment]
Forgot to mention - 
detect-engine.profile: custom  - settings are not taken into effect. low,medium and high are however.

**Comment by inliniac** [comment]
Missing config:
```YAML
detect:
  mpm:
    tcp-packet:
      #shared: false
    tcp-stream:
      #shared: false
    udp-packet:
      #shared: false
    other-ip:
      #shared: false
    http_uri:
      #shared: false
    http_raw_uri:
      #shared: false
    http_header:
      #shared: false
    http_user_agent:
      #shared: false
    http_raw_header:
      #shared: false
    http_method:
      #shared: false
    file_data:
      #shared: false
    http_stat_msg:
      #shared: false
    http_stat_code:
      #shared: false
    http_client_body:
      #shared: false
    http_host:
      #shared: false
    http_raw_host:
      #shared: false
    http_cookie:
      #shared: false
    dns_query:
      #shared: false
```

Shared is a bool, so true or false. True (default) means that rule groups share a single mpm context of the type. Not-shared means each rule group has it's own mpm ctx of the type.

**Comment by inliniac** [comment]
Wrt to that custom setting, looks like I renamed some things :)

```YAML
detect-engine:
  - profile: custom
  - custom-values:
    toclient-groups: 50
    toserver-groups: 50
```

Note that all the other names (e.g. toserver-dp-groups) are ignored now.

**Comment by inliniac** [comment]
Replaced by #1763

**Pull request closed without merging**
