### PR TITLE
Bug 1780 v4

### PR DESCRIPTION
**Pull request by regit**
Rework of #2540 adding comments.

PR builds:
- PR regit: https://buildbot.openinfosecfoundation.org/builders/regit/builds/248
- PR regit-pcap: https://buildbot.openinfosecfoundation.org/builders/regit-pcap/builds/30

### CODE REVIEW

**Comment by inliniac** [comment]
@gozzy can you give this one a test?

**Comment by gozzy** [comment]
@inliniac we're testing v3 patch right now. Seems to work with and without VLANs, but we have not completed checks with VLAN priority and CFI.

**Comment by gozzy** [comment]
Here are the results for v3 patch (v4 is technically the same):
- non-tagged traffic: OK
- tagged traffic without 'priority' and 'CFI' attributes: OK
- tagged traffic with 'priority' and 'CFI' via tcpreplay: OK. We could not test it with IXIA because it processes VLAN parameters in a strange manner (firmware bug?)... However, ARP packets produced by IXIA pass through suricata correctly.

**Comment by inliniac** [comment]
Did you test AF_PACKET v2, v3 or both?

**Comment by inliniac** [comment]
I mean tpacket v2 or v3 of course.

**Comment by gozzy** [comment]
It seemed that we have checked v2.

Tried to enable v3 by specifying "tpacket-v3: yes" in yaml-file now and saw the following after running tcpreplay: packets on 'outgoing' interface contain 2 VLAN tags: the first one is arbitrary (?), the second one is correct. V2 mode doesn't behave like that. It can be easily checked with tcpreplay, no special hardware is required.

**Comment by inliniac** [comment]
Thanks for testing @gozzy. So it seems tpacketv2 works well with this patch. V3 is broken. Wonder where that random data comes from. Any thoughts @regit ?

**Comment by regit** [comment]
@gozzy can you remove the last patch of the branch ? (git reset --hard HEAD^) and see how it goes

**Comment by gozzy** [comment]
@regit ok, I'll give it a try now.

**Comment by gozzy** [comment]
This doesn't seem to affect anything, we still see double tagged packets in tcpdump after tcpreplaying tagged sample.

**Comment by regit** [comment]
@gozzy can you get a try to https://github.com/regit/suricata/tree/bug-1780-v5 ? I've simply removed VLAN fetching from v3..

**Comment by gozzy** [comment]
@regit, works like a charm, no double tags and all fields have expected values.

**Comment by regit** [comment]
ok thanks a lot! I'm going to check the code and resubmit.

**Pull request closed without merging**
