### PR TITLE
decode-events: counters for decode events errors

### PR DESCRIPTION
**Pull request by maurizioabba**
We want to add counters in order to track the number of times we hit a
decode event. A decode event is related to an error in the protocol
decoding over a certain packet.

This patch fist modifies the decode-event list, reordering it in order
to separate single packet events from stream-related events and adding
the prefix "decoder" to decode events.
The counters are created during the decode setup and the relative event
counter is increased every time a packet with the flag PKT_IS_INVALID is
finalized in the decode phase

### CODE REVIEW

**Comment by inliniac** [comment]
Replaces #1854

**Comment by inliniac** [comment]
Do we already have a feature ticket for this? If so can you add the link here? If not can you open the ticket?

**Comment by inliniac** [comment]
Prscript happy:
- PR inliniac-pcap: https://buildbot.openinfosecfoundation.org/builders/inliniac-pcap/builds/378
- PR inliniac: https://buildbot.openinfosecfoundation.org/builders/inliniac/builds/381

**Comment by maurizioabba** [comment]
Feature request: https://redmine.openinfosecfoundation.org/issues/1740

**Comment by inliniac** [comment]
Thanks Maurizio!

**Pull request merged**
