### PR TITLE
Eve alert dump dns fields

### PR DESCRIPTION
**Pull request by fooinha**
The EVE JSON output for a Suricata alert is missing the DNS fields.

This missing information requires that if we've a DNS based Snort rule, we have to correlate the flow_id fields from alert and DNS logged events.

The idea is to dump DNS fields to EVE's alert JSON output.

The alerts for DNS answer packets also logs the queries if question section is available.

Please review this, and consider this idea as an improvement for eve alert logging.

----
Example output:

```javascript
{
  "timestamp": "2016-09-01T20:57:08.943822+0000",
  "flow_id": 8782437618590984000,
  "in_iface": "eth0",
  "event_type": "alert",
  "src_ip": "192.168.65.1",
  "src_port": 53,
  "dest_ip": "172.17.0.4",
  "dest_port": 44566,
  "proto": "UDP",
  "alert": {
    "action": "allowed",
    "gid": 1,
    "signature_id": 8888888,
    "rev": 1,
    "signature": "ET DNS Answer",
    "category": "Potentially Bad Traffic",
    "severity": 2
  },
  "dns": {
    "tx": {
      "answers": [
        {
          "type": "answer",
          "id": 35844,
          "rcode": "NOERROR",
          "rrname": "www.google.com",
          "rrtype": "AAAA",
          "ttl": 280,
          "rdata": "2a00:1450:4003:0801:0000:0000:0000:2004"
        }
      ],
      "queries": [
        {
          "type": "query",
          "id": 35844,
          "rrname": "www.google.com",
          "rrtype": "AAAA",
          "tx_id": 35844
        }
      ],
      "num_tx": 1
    }
  }
}
```
----

No unit tests for this part of the code, nevertheless , I ran it and got this.

....
```text
pass
==== TEST RESULTS ====
PASSED: 3618
FAILED: 0
======================
```
----
I ran valgrind and did some basic tests and did not see any memory leak...

```txt
==22009== 48 bytes in 1 blocks are definitely lost in loss record 145 of 208
==22009==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22009==    by 0x4E43D3D: ??? (in /usr/lib/x86_64-linux-gnu/libmagic.so.1.0.0)
==22009==    by 0x4E447ED: ??? (in /usr/lib/x86_64-linux-gnu/libmagic.so.1.0.0)
==22009==    by 0x7278F2: MagicInit (util-magic.c:83)
==22009==    by 0x4101ED: PostConfLoadedSetup (suricata.c:2431)
==22009==    by 0x4101ED: main (suricata.c:2529)
==22009==
==22009== LEAK SUMMARY:
==22009==    definitely lost: 48 bytes in 1 blocks
==22009==    indirectly lost: 0 bytes in 2 blocks
==22009==      possibly lost: 0 bytes in 0 blocks
==22009==    still reachable: 115,911 bytes in 357 blocks
==22009==         suppressed: 0 bytes in 0 blocks
==22009== Reachable blocks (those to which a pointer was found) are not shown.
==22009== To see them, rerun with: --leak-check=full --show-leak-kinds=all
```

----
A PR to Suricata project is not a simple task, and it would be nice to have some real-life run experience before approval.

### CODE REVIEW

**Comment by inliniac** [comment]
Looks like I also did the perf optimization you did in bb6ff92, so that will have to be dropped.

**Comment by inliniac** [comment]
Can you remove the 'merge' commit and also remove comments like " - Redone in a better way and without memleaks (hopefully)". While it's fine to have comments like this while work is in progress, the final PR should have a bit more confidence :)

**Comment by inliniac** [comment]
It looks like this actually changes the DNS EVE format. Is that correct? If so we will definitely have to look into making sure things are backwards compatible.

**Comment by inliniac** [comment]
In any case the work will have to be rebased against the current master.

Please see https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Github_work_flow#Create-a-new-branch-for-incorporating-feedback for our process around it.

Thanks!

**Comment by fooinha** [comment]
Thanks for the comments. I will try to make cleaner PR's and backward compatible. 
I was already thinking to do so after digging  commit history and looking to commit messages.

**Comment by fooinha** [comment]
Regarding the format of DNS EVE format, it is not really a change.  It's an addition to the alert event. Actually it associates all DNS query/response records found in the packet/flow if a rule
fires.

The current DNS protocol EVE log, creates a new event per response record.
For instance for responses, with multiple records, like this 

```java

;; ANSWER SECTION:
gmail.com.		3201	IN	MX	30 alt3.gmail-smtp-in.l.google.com.
gmail.com.		3201	IN	MX	10 alt1.gmail-smtp-in.l.google.com.
gmail.com.		3201	IN	MX	5 gmail-smtp-in.l.google.com.
gmail.com.		3201	IN	MX	40 alt4.gmail-smtp-in.l.google.com.
gmail.com.		3201	IN	MX	20 alt2.gmail-smtp-in.l.google.com.
```
... it creates multiple events.


```json
{
  "timestamp": "2016-09-08T15:01:53.457442+0000",
  "flow_id": 567849191,
  "in_iface": "eth0",
  "event_type": "dns",
  "src_ip": "192.168.65.1",
  "src_port": 53,
  "dest_ip": "10.10.10.2",
  "dest_port": 44083,
  "proto": "UDP",
  "dns": {
    "type": "answer",
    "id": 48383,
    "rcode": "NOERROR",
    "rrname": "gmail.com",
    "rrtype": "MX",
    "ttl": 3201,
    "rdata": "gmail-smtp-in.l.google.com"
  }
}
{
  "timestamp": "2016-09-08T15:01:53.457442+0000",
  "flow_id": 567849191,
  "in_iface": "eth0",
  "event_type": "dns",
  "src_ip": "192.168.65.1",
  "src_port": 53,
  "dest_ip": "10.10.10.2",
  "dest_port": 44083,
  "proto": "UDP",
  "dns": {
    "type": "answer",
    "id": 48383,
    "rcode": "NOERROR",
    "rrname": "gmail.com",
    "rrtype": "MX",
    "ttl": 3201,
    "rdata": "alt4.gmail-smtp-in.l.google.com"
  }
}
{
  "timestamp": "2016-09-08T15:01:53.457442+0000",
  "flow_id": 567849191,
  "in_iface": "eth0",
  "event_type": "dns",
  "src_ip": "192.168.65.1",
  "src_port": 53,
  "dest_ip": "10.10.10.2",
  "dest_port": 44083,
  "proto": "UDP",
  "dns": {
    "type": "answer",
    "id": 48383,
    "rcode": "NOERROR",
    "rrname": "gmail.com",
    "rrtype": "MX",
    "ttl": 3201,
    "rdata": "alt2.gmail-smtp-in.l.google.com"
  }
}
```

I don't think that we shouldn't do the same for the alerts' events, right? Or should we log multiple times for the same alert for the set of records?

**Comment by fooinha** [comment]
Hi Victor, have you checked my last comment for #2213? I don't know if you
keep being notified after the PR is closed.

No rush.

**Comment by inliniac** [comment]
Right, I see the point. @jasonish any thoughts on the records? The above format will look different in ELK for example: dns.tx.answers... while a normal one is dns.type etc. For the other protocols both cases are the same.

**Comment by jasonish** [comment]
I think the "tx" object is kind of redundant.  Its not a list, which also makes me wonder when would num_tx not be 1?

Without the "tx" object I think its close to what I'd expect to see a DNS event which contained both the request and response together.

**Comment by fooinha** [comment]
I returned a list because at [DNSState struct](https://github.com/inliniac/suricata/blob/master/src/app-layer-dns-common.h#L212) we can see a list of transactions.

Maybe it makes sense to use the only the .curr one, right?

**Comment by fooinha** [comment]
Kibana does not support [Arrays of Objects](https://github.com/elastic/kibana/issues/998) and we are sending answers[] and queries[] ... That's a pity.

The workaround was [this](https://github.com/elastic/kibana/pull/1901).


array-fail

alert-event-json

**Comment by fooinha** [comment]
A fuggly way could be to flat the objects fields into arrays.

flat-dns

**Comment by jasonish** [comment]
I think we should look at how this data would be use.  To me, its extra information on an alert, that will only be viewed when the individual alert is viewed, and I don't care too much about how the data is formatted as I won't be aggregating or sorting - maybe searching on it, but ES handles that fine.

If the above is the normal case I think we do the best formatted JSON as possible and not worry to much about Kibana, as I don't think we'll be generating views that are built from alerts annotated with DNS info.  Maybe I'm wrong here?

We should also consider what a flattened DNS event type may look like where all the responses to a request are handled in a single DNS event entry, and this should be identical.

**Comment by fooinha** [comment]
A fuggly way could be to flat the objects fields into arrays.

flat-dns

**Comment by fooinha** [comment]
Don't sure if I understood the your last phrase.

Something like this?

/* only one answer. flat DNS type */

github com

**Comment by jasonish** [comment]
No, what I'm getting it is we should look at the DNS object as we might look at it for the DNS event IF we were to log one event per request and reply.  Right now a request and reply can result in more than 2 events.  For example, a request for www.google.com will result in one request event, and multiple reply events, one for each address, even tho this transaction only took 2 packets.

So we should probably look at a DNS object that is more or less like your first one without the "tx".  So..

{
    event_type: "alert",
    "alert": {},
    "dns": {
        query: {},
        answers: [
            {},
            {},
        ]

My point being that it be the same as some possible future version of the "DNS" event, and we define it in the most correct way, not confined by Kibana, as I don't know how often Kibana visualizations will dig into this.

What I don't want to see is some "dns" object in an "alert" event that differs from the actual "dns" event.  I understand that for now it has to, due to the multiple events created by a single DNS response - but we should look at it from the perspective of both event types.

**Comment by fooinha** [comment]
A fuggly way could be to flat the objects fields into arrays.

flat-dns

**Comment by fooinha** [comment]
I totally agree with you.

**Comment by fooinha** [comment]
So the final formats could be like this ?

- DNS Event with query only

```json
{
  "timestamp": "2016-09-11T23:06:38.485621+0000",
  "flow_id": 806976632023285,
  "in_iface": "eth0",
  "event_type": "dns",
  "src_ip": "10.10.10.4",
  "src_port": 42385,
  "dest_ip": "192.168.65.1",
  "dest_port": 53,
  "proto": "UDP",
  "dns": {
    "queries": [
      {
        "type": "query",
        "id": 37203,
        "rrname": "gmail.com",
        "rrtype": "MX",
        "tx_id": 37203
      }
    ]
  }
}
```

- Only a DNS Event with multiple response entries

```json
{
  "timestamp": "2016-09-11T23:06:38.501158+0000",
  "flow_id": 806976632023285,
  "in_iface": "eth0",
  "event_type": "dns",
  "src_ip": "192.168.65.1",
  "src_port": 53,
  "dest_ip": "10.10.10.4",
  "dest_port": 42385,
  "proto": "UDP",
  "dns": {
    "answers": [
      {
        "type": "answer",
        "id": 37203,
        "rcode": "NOERROR",
        "rrname": "gmail.com",
        "rrtype": "MX",
        "ttl": 3162,
        "rdata": "alt3.gmail-smtp-in.l.google.com"
      },
      {
        "type": "answer",
        "id": 37203,
        "rcode": "NOERROR",
        "rrname": "gmail.com",
        "rrtype": "MX",
        "ttl": 3162,
        "rdata": "alt2.gmail-smtp-in.l.google.com"
      },
      {
        "type": "answer",
        "id": 37203,
        "rcode": "NOERROR",
        "rrname": "gmail.com",
        "rrtype": "MX",
        "ttl": 3162,
        "rdata": "gmail-smtp-in.l.google.com"
      },
      {
        "type": "answer",
        "id": 37203,
        "rcode": "NOERROR",
        "rrname": "gmail.com",
        "rrtype": "MX",
        "ttl": 3162,
        "rdata": "gmail-smtp-in.l.google.com"
      },
      {
        "type": "answer",
        "id": 37203,
        "rcode": "NOERROR",
        "rrname": "gmail.com",
        "rrtype": "MX",
        "ttl": 3162,
        "rdata": "alt4.gmail-smtp-in.l.google.com"
      },
      {
        "type": "answer",
        "id": 37203,
        "rcode": "NOERROR",
        "rrname": "gmail.com",
        "rrtype": "MX",
        "ttl": 3162,
        "rdata": "alt1.gmail-smtp-in.l.google.com"
      }
    ],
    "queries": [
      {
        "type": "query",
        "id": 37203,
        "rrname": "gmail.com",
        "rrtype": "MX",
        "tx_id": 37203
      }
    ]
  }
}
``` 

-  Alert event with similar ouput

```json
{
  "timestamp": "2016-09-11T23:06:38.501158+0000",
  "flow_id": 806976632023285,
  "in_iface": "eth0",
  "event_type": "alert",
  "src_ip": "192.168.65.1",
  "src_port": 53,
  "dest_ip": "10.10.10.4",
  "dest_port": 42385,
  "proto": "UDP",
  "alert": {
    "action": "allowed",
    "gid": 1,
    "signature_id": 88888888,
    "rev": 1,
    "signature": "All DNS answers",
    "category": "Potentially Bad Traffic",
    "severity": 2
  },
  "dns": {
    "answers": [
      {
        "type": "answer",
        "id": 37203,
        "rcode": "NOERROR",
        "rrname": "gmail.com",
        "rrtype": "MX",
        "ttl": 3162,
        "rdata": "alt3.gmail-smtp-in.l.google.com"
      },
      {
        "type": "answer",
        "id": 37203,
        "rcode": "NOERROR",
        "rrname": "gmail.com",
        "rrtype": "MX",
        "ttl": 3162,
        "rdata": "alt2.gmail-smtp-in.l.google.com"
      },
      {
        "type": "answer",
        "id": 37203,
        "rcode": "NOERROR",
        "rrname": "gmail.com",
        "rrtype": "MX",
        "ttl": 3162,
        "rdata": "gmail-smtp-in.l.google.com"
      },
      {
        "type": "answer",
        "id": 37203,
        "rcode": "NOERROR",
        "rrname": "gmail.com",
        "rrtype": "MX",
        "ttl": 3162,
        "rdata": "alt4.gmail-smtp-in.l.google.com"
      },
      {
        "type": "answer",
        "id": 37203,
        "rcode": "NOERROR",
        "rrname": "gmail.com",
        "rrtype": "MX",
        "ttl": 3162,
        "rdata": "alt1.gmail-smtp-in.l.google.com"
      }
    ],
    "queries": [
      {
        "type": "query",
        "id": 37203,
        "rrname": "gmail.com",
        "rrtype": "MX",
        "tx_id": 37203
      }
    ]
  },
  "payload": "kVOBgAABAAUABAAOBWdtYWlsA2NvbQAADwABwAwADwABAAAMWgAgAB4EYWx0Mw1nbWFpbC1zbXRwLWluAWwGZ29vZ2xlwBLADAAPAAEAAAxaAAkAFARhbHQywC7ADAAPAAEAAAxaAAQABcAuwAwADwABAAAMWgA
JACgEYWx0NMAuwAwADwABAAAMWgAJAAoEYWx0McAuwAwAAgABAAAMxgAGA25zMcA+wAwAAgABAAAMxgAGA25zMsA+wAwAAgABAAAMxgAGA25zM8A+wAwAAgABAAAMxgAGA25zNMA+wFUAAQABAAAA2wAESn3IG8BVABwAAQAAARwA
ECQEaABAAwwAAAAAAAAAABrALgABAAEAAAEbAARKfYUbwC4AHAABAAABBAAQKgAUUEAMDAYAAAAAAAAAG8B6AAEAAQAAARsABK3CSBvAjwABAAEAAACRAARA6aUbwI8AHAABAAABGwAQKgAUUEAQDAgAAAAAAAAAG8ApAAEAAQAAA
RwABEp9FxrAKQAcAAEAAAEbABAkBGgAQAgMAgAAAAAAAAAbwLQAAQABAAAh1wAE2O8iCsCiAAEAAQAAH9EABNjvIArAxgABAAEAACU6AATY7yQKwNgAAQABAAAksQAE2O8mCgAAKRAAAAAAAAAA",
  "payload_printable": ".S...........gmail.com..............Z. ...alt3\rgmail-smtp-in.l.google...........Z.....alt2...........Z...............Z...(.alt4...........Z...\n.alt
1...............ns1.>.............ns2.>.............ns3.>.............ns4.>.U..........J}...U..........$.h.@.......................J}..............*..P@............z........
....H.............@...............*..P@............)..........J}...)..........$.h.@...................!.....\"\n.............. \n........%:....$\n........$.....&\n..).......
.",
  "stream": 0
}
```

**Pull request closed without merging**
