### PR TITLE
Copy the improved strip of double quotes code to every old section

### PR DESCRIPTION
**Pull request by norg**
This fixes also the issue 1638

prscript output:
- PR norg-pcap: https://buildbot.openinfosecfoundation.org/builders/norg-pcap/builds/0
- PR norg: https://buildbot.openinfosecfoundation.org/builders/norg/builds/0

### CODE REVIEW

**Comment by inliniac** [comment]
Couple of comments:
- please add a link to the ticket
- I think a utility function is needed here. We have same code in too many places.
- commit message. We have a convention that we prefix the msg with the sub-system. E.g. "rule parsing: fix quotation parsing issues".

**Comment by inliniac** [comment]
Next step: https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Github_work_flow#Incorporating-feedback :)

**Comment by norg** [comment]
Will do, before i add it to the wrong place, where should the utility function be placed, since we have quite a lot util-* :)

**Comment by inliniac** [comment]
In this case detect-parse.c would probably be the best file.

**Comment by norg** [comment]
Hmm i would have rather put it in util-*.h similar to SCStrdup concept and there are some trade offs depending on the solution you prefer. We either mess with the pointer for "str" (saves memory) or have to work on a copy. Or did you have something totally else in mind when talking about utility function in regard to detect-parse.c?

**Comment by inliniac** [comment]
I think Jason was suggesting we strip the quotes before the per keyword parse functions are called. That may be the best idea so far. That would have to be done in SigParseOptions(). I worry there might be unforeseen side effects though, but it's worth a try.

**Pull request closed without merging**
