### PR TITLE
Feature 2114 redis rpushoutput

### PR DESCRIPTION
**Pull request by securitym0nkey**
This commit implements my own [Feature Request](https://redmine.openinfosecfoundation.org/issues/2114).
No heavy load test done, but in my lab it seems to work.

### CODE REVIEW

**Comment by jasonish** [comment]
Yes, the idea is sound, and is a must do for Logstash I think.  I haven't tested it, but it looks simple enough.  I had planned on testing soon-ish though.

**Comment by fooinha** [comment]
Yes, this idea looks good to me, and it will better for Logstash.

Maybe we should improve the config parsing and error checking for redis mode config key.
It's misleading in several ways.

**Comment by jasonish** [comment]
@securitym0nkey  Just noticed this was made against 3.2.x. Any chance you can rebase it against git master please?

**Comment by securitym0nkey** [comment]
@jasonish I did a 2nd PR #2736 for this change based on master. Any change to get this feature also into the 3.2.x?

**Comment by inliniac** [comment]
This will need a doc update as well.

**Pull request closed without merging**
