### PR TITLE
Store previous value to pvalue variable per thread

### PR DESCRIPTION
**Pull request by jmlich**
Storing of previous value is done just for "Totals" counters. I believe that it should be stored also per thread.

### CODE REVIEW

**Comment by jmlich** [comment]
In other words, the pvalue is currently uninitialized which is in my opinion wrong.

**Comment by inliniac** [comment]
Thanks @jmlich. @jasonish can you check this? Thanks!

**Comment by jmlich** [comment]
I am sorry, but I added next two commits into that pull request. It wasn't intentional.

I am not sure how to split this into two separate issues.

In second issue, I would like to pass "type" of record into the StatsRecord.

**Comment by inliniac** [comment]
This contains a lot of helpful info: https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing

**Comment by jasonish** [comment]
@jmlich Please read up on the URL @inliniac provided.  In short, create a new branch from master, and just include the first commit then submit a new PR.

I also find it helps if there is a bit of explanation of why the PR is being submitted.  In this case, this PR fixes the delta outputs in the JSON stats logging.  Is that what made you create this patch?

**Comment by inliniac** [comment]
Needs some cleanup.

**Pull request closed without merging**
