### PR TITLE
Remove unused cpu affinity config settings in suricata.yaml

### PR DESCRIPTION
**Pull request by pevma**

### CODE REVIEW

**Comment by inliniac** [comment]
I think it would be good to combine changes to the affinity sets with the work in #1783. We can perhaps use the new unified thread names for the affinity sets. @zrasmor any interest in looking at that?

**Comment by pevma** [comment]
Can be interesting - let me know when ready if you need QA-ing/testing - I have plenty of systems to do so.

**Comment by zrasmor** [comment]
@inliniac I will take a look and get back to you shortly

**Comment by inliniac** [comment]
Needs to be part of a more integrated approach wrt the affinity settings.

**Pull request closed without merging**
