### PR TITLE
app-layer-ssl: Validity dates from TLS certificates (v15)

### PR DESCRIPTION
**Pull request by thus**
Get validity dates (notBefore and notAfter) from TLS certificates.

New detection keywords (tls_cert_notbefore and tls_cert_notafter), added validity dates to extended JSON log and extended TLS log output, and new lua functions TlsGetCertNotBefore() and TlsGetCertNotAfter().

Updates:
- Removed functionality that doesn't work on BSD

This PR fixes the following issue:
- https://redmine.openinfosecfoundation.org/issues/1583

Prscript:
- PR thus-pcap: https://buildbot.openinfosecfoundation.org/builders/thus-pcap/builds/48
- PR thus: https://buildbot.openinfosecfoundation.org/builders/thus/builds/48

### CODE REVIEW

**Comment by inliniac** [comment]
Cygwin doesn't like this at all:
<pre>
Test ValidityTestParse01                                          : FAILED
Test ValidityTestParse03                                          : FAILED
Test ValidityTestParse05                                          : [724] 23/9/2016 -- 18:04:57 - (detect-tls-cert-validity.c:219) <Error> (DetectTlsValidityParse) -- [ERRCODE: SC_ERR_PCRE_MATCH(2)] - Parse error A
pass
Test ValidityTestParse07                                          : [724] 23/9/2016 -- 18:04:57 - (detect-tls-cert-validity.c:219) <Error> (DetectTlsValidityParse) -- [ERRCODE: SC_ERR_PCRE_MATCH(2)] - Parse error 1430000000<>
pass
Test ValidityTestParse09                                          : [724] 23/9/2016 -- 18:04:57 - (detect-tls-cert-validity.c:219) <Error> (DetectTlsValidityParse) -- [ERRCODE: SC_ERR_PCRE_MATCH(2)] - Parse error 
pass
Test ValidityTestParse11                                          : pass
Test ValidityTestParse13                                          : FAILED
Test ValidityTestParse15                                          : FAILED
Test ValidityTestParse17                                          : pass
Test ValidityTestParse19                                          : pass
Test ValidityTestParse21                                          : pass
Test ValidityTestParse23                                          : pass
Test ValidityTestDetect01                                         : pass
Test ValidityTestParse02                                          : FAILED
Test ValidityTestParse04                                          : FAILED
Test ValidityTestParse06                                          : [724] 23/9/2016 -- 18:04:57 - (detect-tls-cert-validity.c:284) <Error> (DetectTlsValidityParse) -- [ERRCODE: SC_ERR_INVALID_ARGUMENT(13)] - Range specified but mode also set
pass
Test ValidityTestParse08                                          : [724] 23/9/2016 -- 18:04:57 - (detect-tls-cert-validity.c:219) <Error> (DetectTlsValidityParse) -- [ERRCODE: SC_ERR_PCRE_MATCH(2)] - Parse error <>1430000000
pass
Test ValidityTestParse10                                          : pass
Test ValidityTestParse12                                          : FAILED
Test ValidityTestParse14                                          : FAILED
Test ValidityTestParse16                                          : pass
Test ValidityTestParse18                                          : pass
Test ValidityTestParse20                                          : pass
Test ValidityTestParse22                                          : pass

</pre>

**Comment by inliniac** [comment]
OpenBSD 5.4 fails on the same tests. OSX and FreeBSD are now fine.

**Comment by thus** [comment]
Looking at libc for both Cygwin and OpenBSD 5.4, it seems that neither of them support %s (seconds since epoch) in strptime.

We can solve this by not using SCStringPatternToTime if the rule contains a epoch timestamp, since this is what we ultimately want to end up with after all.

**Comment by inliniac** [comment]
On 23-09-16 23:03, Mats Klepsland wrote:
> Looking at libc for both Cygwin and OpenBSD 5.4, it seems that neither
> of them support %s (seconds since epoch) in strptime.
> 
> We can solve this by not using SCStringPatternToTime if the rule
> contains a epoch timestamp, since this is what we ultimately want to end
> up with after all.

I guess we won't need second accuracy do we?

**Comment by thus** [comment]
We don't need seconds, that's probably overkill. However, it would probably be useful to be able to use unix seconds (epoch) in rules, e.g:
```
tls_cert_notafter:<1474664965;
```

**Comment by thus** [comment]
Replaced by #2277

**Pull request closed without merging**
