### PR TITLE
Dev tls cipher suite v11

### PR DESCRIPTION
**Pull request by fooinha**
@thus, thanx for your review.

New PR with style and code cleanup and review fixes. 
I also implemented, eve logging and client cipher suite in tls.log.

 Only missing:
-  LUA scripting functions.
- Read from comma separated file, ... yaml not done yet.

----

**Feature**

- Allows tls app-layer rules to match TLS handshake cypher suites
Example rules:

```
alert tls any any -> any any
(msg:"SURICATA TLS CIPHER SUITE CLIENT"; 
tls_cipher_suite:client,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,0xcca9;
sid:66666666; 
rev:1;
)
```
```
alert tls any any -> any any 
(msg:"SURICATA TLS CIPHER SUITE SERVER";
tls_cipher_suite:server,0xcca8;
sid:66666667;
rev:1;
)
```

- Custom tls logging for server cipher suite -> %C 
- Custom tls logging for client cipher suite -> %c
- Eve logging for tls cipher suites 
- Load list from configuration file (tls.cipher-suites.config) configured at suricata.yaml
   - Fallback to default values if configuration file load is not done.

- Documentation

Replaces #2657 / #2671 / #2685 /  #2707 / #2754

fyi, @thus

### CODE REVIEW

**Comment by inliniac** [comment]
<pre>
==16875==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 2 byte(s) in 1 object(s) allocated from:
    #0 0x4c301b in __interceptor_malloc (/home/victor/qa/buildbot/donkey/z600fuzz/Private/src/suricata+0x4c301b)
    #1 0x837279 in TLSDecodeHandshakeHello /home/victor/qa/buildbot/donkey/z600fuzz/Private/src/app-layer-ssl.c:321:48
    #2 0x82ffd3 in SSLv3ParseHandshakeType /home/victor/qa/buildbot/donkey/z600fuzz/Private/src/app-layer-ssl.c:471:18
    #3 0x82d05d in SSLv3ParseHandshakeProtocol /home/victor/qa/buildbot/donkey/z600fuzz/Private/src/app-layer-ssl.c:682:14
    #4 0x828482 in SSLv3Decode /home/victor/qa/buildbot/donkey/z600fuzz/Private/src/app-layer-ssl.c:1316:22
    #5 0x8203b6 in SSLDecode /home/victor/qa/buildbot/donkey/z600fuzz/Private/src/app-layer-ssl.c:1484:30
    #6 0x819ef7 in SSLParseServerRecord /home/victor/qa/buildbot/donkey/z600fuzz/Private/src/app-layer-ssl.c:1576:12
    #7 0x7a2603 in AppLayerParserParse /home/victor/qa/buildbot/donkey/z600fuzz/Private/src/app-layer-parser.c:1052:13
    #8 0x5389fe in TCPProtoDetect /home/victor/qa/buildbot/donkey/z600fuzz/Private/src/app-layer.c:421:17
    #9 0x535531 in AppLayerHandleTCPData /home/victor/qa/buildbot/donkey/z600fuzz/Private/src/app-layer.c:561:13
    #10 0x117e050 in ReassembleUpdateAppLayer /home/victor/qa/buildbot/donkey/z600fuzz/Private/src/stream-tcp-reassemble.c:1030:13
    #11 0x117b4a5 in StreamTcpReassembleAppLayer /home/victor/qa/buildbot/donkey/z600fuzz/Private/src/stream-tcp-reassemble.c:1102:12
    #12 0x118a981 in StreamTcpReassembleHandleSegmentUpdateACK /home/victor/qa/buildbot/donkey/z600fuzz/Private/src/stream-tcp-reassemble.c:1649:9
    #13 0x1189df2 in StreamTcpReassembleHandleSegment /home/victor/qa/buildbot/donkey/z600fuzz/Private/src/stream-tcp-reassemble.c:1688:9
    #14 0x10e61df in StreamTcpPacketStateFinWait1 /home/victor/qa/buildbot/donkey/z600fuzz/Private/src/stream-tcp.c:2743:13
    #15 0x10b7b91 in StreamTcpPacket /home/victor/qa/buildbot/donkey/z600fuzz/Private/src/stream-tcp.c:4555:20
    #16 0x11228d9 in StreamTcp /home/victor/qa/buildbot/donkey/z600fuzz/Private/src/stream-tcp.c:4914:11
    #17 0xde6ee1 in FlowWorker /home/victor/qa/buildbot/donkey/z600fuzz/Private/src/flow-worker.c:215:9
    #18 0x11d8354 in TmThreadsSlotVarRun /home/victor/qa/buildbot/donkey/z600fuzz/Private/src/tm-threads.c:128:17
    #19 0x11f8711 in TmThreadsSlotVar /home/victor/qa/buildbot/donkey/z600fuzz/Private/src/tm-threads.c:585:17
    #20 0x7f8a4bab3183 in start_thread /build/eglibc-MjiXCM/eglibc-2.19/nptl/pthread_create.c:312
</pre>

**Comment by inliniac** [comment]
Seems we still have the same issue.

**Comment by fooinha** [comment]
replaced by #2768 ...

**Comment by fooinha** [comment]
replaced by #2768 ...

**Pull request closed without merging**
