### PR TITLE
Lua: smtp-support implemented, incorporated feedback from v3

### PR DESCRIPTION
**Pull request by tobiass1**
Implemented support for matching on SMTP traffic from lua scripts.
This enables availibility to MIME fields,
MailFrom attribute, recipients list.

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/1775

Fixes changes suggested in #2119

### CODE REVIEW

**Comment by pevma** [comment]
@tobiass1  - whenever upon merge - it will be helpful to all users if you could please include some basic usage examples on our wiki.

**Comment by tobiass1** [comment]
@pevma - I agree, i have some documentation and basic user examples prepared and ready to be committed to the wiki/docs of jasonish. I'm just not entirely sure on how he wants it formatted and committed.

**Comment by pevma** [comment]
@tobiass1 - some guideline can be ref here - https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Converting_Wiki_Documentation_to_Sphinx

**Comment by tobiass1** [comment]
@pevma - Thanks! Will have a look and commit the examples asap.

**Comment by inliniac** [comment]
The git message needs some work:
1. it not descriptive at all (what you had originally here https://github.com/inliniac/suricata/pull/2055/commits/d02567f02223e1229ef9a90fc8cfd325e5ed1e57 was better except the link)
2. it contains irrelevant references to a v3. When someone checks out our git tree this has no meaning. Changes vs previous pull requests should be listed in the pull request itself, not the commits.

https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Code_Submission_Quality_Criteria#Commits

Btw it seems somewhere on long the way the attachment logic was removed. That is definitely something that should be mentioned in the pull request in the changes since last pr.

**Pull request closed without merging**
