### PR TITLE
Next 30x v1

### PR DESCRIPTION
**Pull request by inliniac**
@regit @norg @jasonish please have a look if anything is missing. This is to be 3.0.2

### CODE REVIEW

**Comment by norg** [comment]
Looks fine to me, all my other commits should be just 3.1

**Comment by pevma** [comment]
@norg  - ok , cause i was about to ask if we didn't miss  - https://github.com/inliniac/suricata/pull/2154

**Comment by regit** [comment]
I think we could add 4defc5acc21e92b53d6993e6133871e3636a9193 which is fixing a problem for some setup and should not have any negative impact.

**Comment by jasonish** [comment]
Looks fine to me. Anything I have is pending for 3.1 as well.

**Comment by inliniac** [comment]
Great points, added those in #2158

**Pull request closed without merging**
