### PR TITLE
Enip feature 1495 v3

### PR DESCRIPTION
**Pull request by kwong-solana**
rebased to master.  Add SCADA EtherNet/IP(ENIP) and Common Industrial Support (CIP )

### CODE REVIEW

**Comment by hubayirp** [comment]
+1

**Comment by inliniac** [comment]
The approach here seems to be to create a decoder module that doesn't actually run in our decoding stage, but instead in the detection context.

I think an approach like our DNS UDP (app-layer) parsing would make a lot of sense here, as it hands you the API's to more complex detection logic, plus it makes logging possible. I think it would be great to add CIP and EINP logging to our eve-log output.

It's unclear to me if this should inspect TCP as well? If so, the app-layer approach will be unavoidable to deal with stream reassembly.

**Comment by inliniac** [comment]
The PR/branch will have to be improved wrt style and such btw:
- commits and commit messages: https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Code_Submission_Quality_Criteria
- coding style: https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Coding_Style

**Comment by kwong-solana** [comment]
Thanks very much for the feedback.  Can you please give an example of issues in the coding style? We used other code in src and your guide as an examples.

**Comment by jasonish** [comment]
I took a quick look at ENIP/CIP.  It looks likes it is always carried over TCP or UDP, in which case it should really go into the app-layer.  To start with, you should probably break this out into 2 areas, the app-layer and the detection.

Per @inliniac 's suggestion, the DNS app-layer is probably a good point of reference to start with.  In app-layer-dns-tcp.c you will see RegisterDNSTCPParsers where you can register  your application layer decoding logic on the necessary ports.  You then register request and response handlers, and Suricata will pass you the reassembled stream buffers.

Your app-layer will then decode ethernet/ip, and cip and record the data into a transaction object, which will then be accessible to the detection layer.  You will probably also want to register a protocol, such as "enip" so you can write rules like "alert enip...".

Another example to look at is the modbus support (app-layer-modbus.*, detect-modbus.*).  And if you want to see an in progress app-layer, detection and logging checkout the ongoing DNP3 work at https://github.com/jasonish/suricata/tree/ish-dnp3 - it might make it easier to pull out whats needed to hook it all up by diffing that against master.

I have yet to take a closer look at the code, but I think getting it organized and hooked in properly would be a good start.

**Comment by kwong-solana** [comment]
Thanks again we will look into this.  We started this by using the Packet Inspection Module example as a base and started from there.  We will look into doing it app-layer style.   BTW, the other links for extending suricata on the website are dead.

**Comment by kwong-solana** [comment]
I was looking at the example rules you have for modbus and dns and was wondering how you would be able to deal with vendor specific type ENIP/CIP rules.  CIP packets can have Service, Class and Attribute defined by numeric value.  Some of these are defined by ODVA but for the most part, the manufacturer specifies them and builds equipment  using their own additions.

**Comment by jasonish** [comment]
> I was looking at the example rules you have for modbus and dns and was wondering how you would be able to deal with vendor specific type ENIP/CIP rules. CIP packets can have Service, Class and Attribute defined by numeric value. Some of these are defined by ODVA but for the most part, the manufacturer specifies them and builds equipment using their own additions.

I don't think thats too much of a problem.  So you have a keyword, cip_server:<numeric_value>...  Obviously we can't ship vendor specific ones as we don't know what they are.  So it would be up the end user to write those rules - if thats what you are asking?

**Comment by kwong-solana** [comment]
To clarify, our rules have keyword "cip_service" with a comma delimited numeric parameter string for the Service, Class(optional) and Attribute (optional).  For example:  "cip_service:4,300,16"  With detects a CIP packet with Service=4, Class=300 and Attribute=16.  These services,classes,and attribute are unknown to us and can exist out in the field, but we need to support them anyways

**Comment by inliniac** [comment]
@kwong-solana wrt style, things that I noticed: indent issues (should be 4 spaces), structure names (are all caps), function comments (should use doxygen format).

**Comment by kwong-solana** [comment]
Hi All, have you gotten a chance to determine whether it is possible to do an app-layer implementation with the types of rules we want to support?  I have looked at the modbus and dns rules and can see that they deal with defined events whereas ENIP/CIP allows vendors to decide what is possible.

**Comment by jasonish** [comment]
> Hi All, have you gotten a chance to determine whether it is possible to do an app-layer implementation with the types of rules we want to support? I have looked at the modbus and dns rules and can see that they deal with defined events whereas ENIP/CIP allows vendors to decide what is possible.

Honestly I think this is up to you.  The app-layer approach doesn't put any more limitations on what you've tried to do already, its just a better place to do the protocol decoding as you will get a normalized stream data.

I'm still not sure I understand what you are after.  Basically you will have to hard code some keywords for detection, but the contents of those keywords could give you the flexibility of what you need.

Modbus is one example, eg) "modbus: access write coils, address > 500;" is almost like a small language within the value of the keyword.  The DNP3 approach is a little more strict where the keyword denotes what data is being looked for, and the value of the keyword is just match parameters.

So you'll have to find what you need to do to provide the flexibility required to look at vendor specific events.  It might be as simple as just allowing unknown values to be used.  For example, I think in DNP3, vendors can use vendor specific function codes (I may be wrong here), but the DNP3 layer doesn't care that its vendor specific, it will just look for it.

But if the vendor is going to send vendor specific data objects over the wire, then there is little you can do to provide support for that within Suricata, short of hooking into Lua and writing Lua scripts that would do the custom decoding required.

Hope that helps.

**Comment by kwong-solana** [comment]
Ok, I think I understand what you are saying.  It's not that I should scrap all the work I did with keyword style rules, I should be adding this to app-layer handling so it can handle stream data (seen in detect-modbus.c).  Also future-wise, I can add protocol specific events to my rules (seen in applayer-mobus.c).  ex. app-layer-event:enip-event:invalid-path

**Comment by kwong-solana** [comment]
Hi All, our team was wondering if you can pull in the ENIP/CIP feature as is into master.  This would be  a first cut so that in some point in the future we can proceed with the app layer implementation.  More features should follow afterwards.  We have done extensive testing using various security tools and it has been successful.

**Comment by inliniac** [comment]
The issue I see is that the current code has a fundamental weakness: it's trivial to evade it using very low tech tricks (tcp session splicing). This won't be addressed in a simple incremental fix/update, but will require significant re-factoring which will essentially remove most of the current implementation.

By merging it now it could end up in a stable release before you've been able to improve it, which is simply not acceptable. That would force me to rip it out again, etc. So it makes much more sense to leave this out of tree until it's in better shape.

Conclusion: I won't merge this iteration, sorry.

**Pull request closed without merging**
