### PR TITLE
netmap: support non-equal count of Rx and Tx rings on interface

### PR DESCRIPTION
**Pull request by gureedo**
Removed restriction on interfaces with non-equal count of Rx and Tx rings.

### CODE REVIEW

**Comment by inliniac** [comment]
Could you expand on what this means? Is this addressing some of the things Oliver ran into?

**Comment by gureedo** [comment]
No, it's absolutely different improvement.
Just want to remove this limitation for future.
Netmap does not guarantees that NIC will have equal number of transmit and receive rings.
Current code code can't work with such NIC.

I've found that my code will not work in autofp mode. Sorry for that, I'll make another pull request to fix it in couple of days.
Also I will implement ability to specify OS network stack as copy endpoint, there will be one more pull request for this.

**Comment by inliniac** [comment]
I see, thanks. Could you add explanations like this to the commits themselves? That makes it easier to trace back changes later.

**Comment by gureedo** [comment]
Amended commit with new comments.

**Comment by inliniac** [comment]
Please don't update existing PR-branches, instead create a new branch, update it and create a new PR. Thanks.

**Comment by gureedo** [comment]
Ok, will open new PR. Just interesting why it's should not be updated?

**Pull request closed without merging**
